Kyle's Doxygen Test: include/bin_commandss_execution.h File Reference
bin_commandss_execution.h File Reference
#include "util.h"
Functions
char * find_command (char **env, char *cmd)
Function Documentation
find_command()
char * find_command (char ** env, char * cmd)
Definition at line 40 of file find_command.c.
{
    int     y;
    char    **path;
    char    *final_path;
    y = 0;
    while (env[y] && ft_strncmp(env[y], "PATH=", 5) != 0)
        y++;
    if (checker_path(env[y], cmd))
        return (checker_path(env[y], cmd));
    path = ft_split(env[y] + 5, ':');
    y = 0;
    while (path[y])
    {
        final_path = get_final_path(path[y], cmd);
        if (access(final_path, X_OK) == 0)
        {
            free_double_pointer(path);
            return (final_path);
        }
        free(final_path);
        y++;
    }
    free_double_pointer(path);
    return (NULL);
}
References checker_path(), free_double_pointer(), ft_split(), ft_strncmp(), and get_final_path().
Referenced by bin_execute().