Kyle's Doxygen Test: src/command_functs.c File Reference
command_functs.c File Reference
#include "../include/bin_commandss_execution.h"
#include "../include/command.h"
#include "../include/environment.h"
#include "../list/list.h"
#include "../libft/libft.h"
#include <signal.h>
Functions
static char * serialize_arg (void *arg_ptr)
void bin_execute (t_command *cmd, t_gen_list *envioroment)
void cd_execute (t_command *command, t_gen_list *environment)
void pwd_execute (t_command *command, t_gen_list *envioroment)
void env_execute (t_command *command, t_gen_list *envioroment)
void export_execute (t_command *command, t_gen_list *envioroment)
void unset_execute (t_command *command, t_gen_list *envioroment)
void echo_execute (t_command *command, t_gen_list *envioroment)
Function Documentation
bin_execute()
void bin_execute (t_command * cmd, t_gen_list * envioroment)
Definition at line 28 of file command_functs.c.
{
    char **cmd2;
    char **env;
    char *path;
    if (!cmd || !cmd->args || !cmd->args->head)
    {
        perror("No command args ");
        exit(1);
    }
    env = env_serialize(envioroment);
    cmd2 = serialize_to_string_array(cmd->args,serialize_arg);
    path = find_command(env, cmd2[0]);
    if (!path)
    {
        perror("Path not found ");
        free_double_pointer(cmd2);
        exit(127);
    }
    signal(SIGINT, SIG_DFL);
    signal(SIGQUIT, SIG_DFL);
    execve(path, cmd2, env);
    perror("Failed to execute command ");
    free(path);
    free_double_pointer(cmd2);
    exit(1);
}
References s_command::args, env_serialize(), find_command(), free_double_pointer(), s_gen_list::head, serialize_arg(), and serialize_to_string_array().
Referenced by get_command_function().
cd_execute()
void cd_execute (t_command * command, t_gen_list * environment)
Definition at line 61 of file command_functs.c.
{
    t_iter it;
    char *old_directory;
    char *target;
    char *joined_path;
    if (!command->args || command->args->size < 2)
    {
        fprintf(stderr, "cd: missing argument\n");
        return;
    }
    old_directory = env_get(environment, "PWD");
    it = iter_start(command->args);
    iter_next(&it);
    target = iter_next(&it);
    if (access(target, F_OK) == 0)
    {
        if (chdir(target) == -1)
        {
            perror("cd");
            free(old_directory);
            return;
        }
        if (old_directory)
            env_set(environment, old_directory, "OLDPWD");
        env_set(environment, ft_strdup(target), "PWD");
        free(old_directory);
        return;
    }
    if (old_directory)
    {
        joined_path = ft_strjoin(old_directory, target);
        if (access(joined_path, F_OK) == 0)
        {
            if (chdir(joined_path) == -1)
            {
                perror("cd");
                free(joined_path);
                free(old_directory);
                return;
            }
            env_set(environment, old_directory, "OLDPWD");
            env_set(environment, joined_path, "PWD");
            free(joined_path);
            free(old_directory);
            return;
        }
        free(joined_path);
    }
    fprintf(stderr, "cd: no such file or directory: %s\n", target);
    free(old_directory);
}
References s_command::args, env_get(), env_set(), ft_strdup(), ft_strjoin(), iter_next(), iter_start(), and s_gen_list::size.
Referenced by execute_commands_with_pipes(), and get_command_function().
echo_execute()
void echo_execute (t_command * command, t_gen_list * envioroment)
Definition at line 174 of file command_functs.c.
{
    t_node *current_node;
    int newline = 1;
    size_t len;
    if (!command || !command->args || !command->args->head)
        return;
    current_node = command->args->head->next; // primer argumento real
    if (!current_node)
        return;
    // Comprobar -n usando ft_strncmp
    len = ft_strlen((char *)current_node->value);
    if (len == 2 && ft_strncmp((char *)current_node->value, "-n", 2) == 0)
    {
        newline = 0;
        current_node = current_node->next;
    }
    while (current_node)
    {
        ft_printf("%s", (char *)current_node->value);
        if (current_node->next)
            ft_printf(" ");
        current_node = current_node->next;
    }
    if (newline)
        ft_printf("\n");
    // No hacemos exit aqu; solo en hijos si se hace fork
    exit(0);
}
References s_command::args, ft_printf(), ft_strlen(), ft_strncmp(), s_gen_list::head, s_node::next, and s_node::value.
Referenced by get_command_function().
env_execute()
void env_execute (t_command * command, t_gen_list * envioroment)
Definition at line 125 of file command_functs.c.
{
    char **serialized_env;
    int i;
    if (!command)
    {
        perror("env :");
        return;
    }
    serialized_env = env_serialize(envioroment);
    i = 0;
    while(i < envioroment->size)
    {
        printf("%s", serialized_env[i]);
        i++;
    }
    free_double_pointer(serialized_env);
}
References env_serialize(), and free_double_pointer().
Referenced by get_command_function().
export_execute()
void export_execute (t_command * command, t_gen_list * envioroment)
Definition at line 143 of file command_functs.c.
{
    t_node *current_node;
    char **new_variable;
    if (!command || !command->args || !envioroment)
        return;
    current_node = command->args->head->next;
    if (!current_node || !current_node->value)
        return;
    new_variable = ft_split2(current_node->value, '=');
    if (!new_variable || !new_variable[0] || !new_variable[1])
        return;
    env_set(envioroment, new_variable[0], new_variable[1]);
    size_t i = 0;
    while (i < 2)
    {
        free(new_variable[i]);
        i++;
    }
    free(new_variable);
}
References s_command::args, env_set(), ft_split2(), s_gen_list::head, s_node::next, and s_node::value.
Referenced by execute_commands_with_pipes(), and get_command_function().
pwd_execute()
void pwd_execute (t_command * command, t_gen_list * envioroment)
Definition at line 115 of file command_functs.c.
{
    char *current_dir;
    if (command == NULL)
        return ;
    current_dir = env_get(envioroment, "PWD");
    printf("%s\n", current_dir);
    free(current_dir);
    exit(0);
}
References env_get().
Referenced by get_command_function().
serialize_arg()
static char * serialize_arg (void * arg_ptr) static
Definition at line 21 of file command_functs.c.
{
    char *arg = (char *) arg_ptr;
    return (ft_strdup(arg));
}
References ft_strdup().
Referenced by bin_execute().
unset_execute()
void unset_execute (t_command * command, t_gen_list * envioroment)
Definition at line 167 of file command_functs.c.
{
    t_node  *current_node;
    current_node = command->args->head->next;
    env_unset(envioroment, (char *)current_node->value);
}
References s_command::args, env_unset(), s_gen_list::head, s_node::next, and s_node::value.
Referenced by execute_commands_with_pipes(), and get_command_function().