Kyle's Doxygen Test: src/command.c File Reference
command.c File Reference
#include "../include/command.h"
#include "../include/redirect_asignation.h"
#include "../list/list.h"
#include "../libft/libft.h"
#include "stdlib.h"
#include <stdio.h>
Functions
t_command * init_command (t_gen_list *args, t_command_funct funct, t_gen_list *redirects)
void destroy_command (void *command_to_delete)
Function Documentation
destroy_command()
void destroy_command (void * command_to_delete)
Definition at line 21 of file command.c.
{
    t_command   *command;
    command = (t_command *)command_to_delete;
    if (command->args)
        destroy_gen_list(command->args, free);
    if (command->redirects)
        destroy_gen_list(command->redirects, destroy_redirect);
    ;
    free(command);
}
References s_command::args, destroy_gen_list(), destroy_redirect(), and s_command::redirects.
Referenced by main(), and parse_tokens_to_commands().
init_command()
t_command * init_command (t_gen_list * args, t_command_funct funct, t_gen_list * redirects)
Definition at line 9 of file command.c.
{
    t_command   *new_command;
    new_command = ft_calloc(1, sizeof(t_command));
    new_command->args = args;
    new_command->command_funct = funct;
    new_command->redirects = redirects;
    return (new_command);
}
References s_command::args, s_command::command_funct, ft_calloc(), and s_command::redirects.
Referenced by parse_tokens_to_commands().