Kyle's Doxygen Test: include/command.h File Reference
command.h File Reference
Module that contains the necesary functionality to create and execute commands.
#include "../list/list.h"
Classes
struct s_command
Typedefs
typedef struct s_command t_command
typedef void(* t_command_funct) (t_command *, t_gen_list *)
Functions
t_command * init_command (t_gen_list *args, t_command_funct funct, t_gen_list *redirects)
void destroy_command (void *command_to_delete)
void pwd_execute (t_command *command, t_gen_list *envioroment)
void bin_execute (t_command *cmd, t_gen_list *envioroment)
void cd_execute (t_command *command, t_gen_list *envioroment)
void export_execute (t_command *command, t_gen_list *envioroment)
void unset_execute (t_command *command, t_gen_list *envioroment)
void env_execute (t_command *command, t_gen_list *envioroment)
void echo_execute (t_command *command, t_gen_list *envioroment)
void execute_commands_with_pipes (t_gen_list *commands, t_gen_list *env)
Executes the commands in the given list in order as child processes linking their input and output with the corresponding pipes.
Detailed Description
Module that contains the necesary functionality to create and execute commands.
Definition in file command.h.
Typedef Documentation
t_command
typedef struct s_command t_command
Definition at line 22 of file command.h.
t_command_funct
typedef void(* t_command_funct) (t_command *, t_gen_list *)
Definition at line 24 of file command.h.
Function Documentation
bin_execute()
void bin_execute (t_command * cmd, t_gen_list * envioroment)
Definition at line 28 of file command_functs.c.
{
    char **cmd2;
    char **env;
    char *path;
    if (!cmd || !cmd->args || !cmd->args->head)
    {
        perror("No command args ");
        exit(1);
    }
    env = env_serialize(envioroment);
    cmd2 = serialize_to_string_array(cmd->args,serialize_arg);
    path = find_command(env, cmd2[0]);
    if (!path)
    {
        perror("Path not found ");
        free_double_pointer(cmd2);
        exit(127);
    }
    signal(SIGINT, SIG_DFL);
    signal(SIGQUIT, SIG_DFL);
    execve(path, cmd2, env);
    perror("Failed to execute command ");
    free(path);
    free_double_pointer(cmd2);
    exit(1);
}
References s_command::args, env_serialize(), find_command(), free_double_pointer(), s_gen_list::head, serialize_arg(), and serialize_to_string_array().
Referenced by get_command_function().
cd_execute()
void cd_execute (t_command * command, t_gen_list * envioroment)
Definition at line 61 of file command_functs.c.
{
    t_iter it;
    char *old_directory;
    char *target;
    char *joined_path;
    if (!command->args || command->args->size < 2)
    {
        fprintf(stderr, "cd: missing argument\n");
        return;
    }
    old_directory = env_get(environment, "PWD");
    it = iter_start(command->args);
    iter_next(&it);
    target = iter_next(&it);
    if (access(target, F_OK) == 0)
    {
        if (chdir(target) == -1)
        {
            perror("cd");
            free(old_directory);
            return;
        }
        if (old_directory)
            env_set(environment, old_directory, "OLDPWD");
        env_set(environment, ft_strdup(target), "PWD");
        free(old_directory);
        return;
    }
    if (old_directory)
    {
        joined_path = ft_strjoin(old_directory, target);
        if (access(joined_path, F_OK) == 0)
        {
            if (chdir(joined_path) == -1)
            {
                perror("cd");
                free(joined_path);
                free(old_directory);
                return;
            }
            env_set(environment, old_directory, "OLDPWD");
            env_set(environment, joined_path, "PWD");
            free(joined_path);
            free(old_directory);
            return;
        }
        free(joined_path);
    }
    fprintf(stderr, "cd: no such file or directory: %s\n", target);
    free(old_directory);
}
References s_command::args, env_get(), env_set(), ft_strdup(), ft_strjoin(), iter_next(), iter_start(), and s_gen_list::size.
Referenced by execute_commands_with_pipes(), and get_command_function().
destroy_command()
void destroy_command (void * command_to_delete)
Definition at line 21 of file command.c.
{
    t_command   *command;
    command = (t_command *)command_to_delete;
    if (command->args)
        destroy_gen_list(command->args, free);
    if (command->redirects)
        destroy_gen_list(command->redirects, destroy_redirect);
    ;
    free(command);
}
References s_command::args, destroy_gen_list(), destroy_redirect(), and s_command::redirects.
Referenced by main(), and parse_tokens_to_commands().
echo_execute()
void echo_execute (t_command * command, t_gen_list * envioroment)
Definition at line 174 of file command_functs.c.
{
    t_node *current_node;
    int newline = 1;
    size_t len;
    if (!command || !command->args || !command->args->head)
        return;
    current_node = command->args->head->next; // primer argumento real
    if (!current_node)
        return;
    // Comprobar -n usando ft_strncmp
    len = ft_strlen((char *)current_node->value);
    if (len == 2 && ft_strncmp((char *)current_node->value, "-n", 2) == 0)
    {
        newline = 0;
        current_node = current_node->next;
    }
    while (current_node)
    {
        ft_printf("%s", (char *)current_node->value);
        if (current_node->next)
            ft_printf(" ");
        current_node = current_node->next;
    }
    if (newline)
        ft_printf("\n");
    // No hacemos exit aqu; solo en hijos si se hace fork
    exit(0);
}
References s_command::args, ft_printf(), ft_strlen(), ft_strncmp(), s_gen_list::head, s_node::next, and s_node::value.
Referenced by get_command_function().
env_execute()
void env_execute (t_command * command, t_gen_list * envioroment)
Definition at line 125 of file command_functs.c.
{
    char **serialized_env;
    int i;
    if (!command)
    {
        perror("env :");
        return;
    }
    serialized_env = env_serialize(envioroment);
    i = 0;
    while(i < envioroment->size)
    {
        printf("%s", serialized_env[i]);
        i++;
    }
    free_double_pointer(serialized_env);
}
References env_serialize(), and free_double_pointer().
Referenced by get_command_function().
execute_commands_with_pipes()
void execute_commands_with_pipes (t_gen_list * commands, t_gen_list * env)
Executes the commands in the given list in order as child processes linking their input and output with the corresponding pipes.
Parameters
commands Command list to execute
env Environment variable list that the commands may need.
Definition at line 21 of file pipe.c.
{
    size_t n = commands->size;
    int (*pipes)[2] = malloc(sizeof(int[2]) * (n - 1));
    if (n > 1 && !pipes)
        return;
    for (size_t i = 0; i < n - 1; i++)
        pipe(pipes[i]);
    t_iter it = iter_start(commands);
    t_command *cmd;
    pid_t *pids = malloc(sizeof(pid_t) * n);
    size_t i = 0;
    while ((cmd = iter_next(&it)) != NULL)
    {
        if (cmd->command_funct == cd_execute ||
            cmd->command_funct == export_execute ||
            cmd->command_funct == unset_execute)
        {
            cmd->command_funct(cmd, env);
            i++;
            continue;
        }
        pid_t pid = fork();
        if (pid == 0)
        {
            if (i > 0)
            {
                dup2(pipes[i - 1][0], STDIN_FILENO);
            }
            if (i < n - 1)
            {
                dup2(pipes[i][1], STDOUT_FILENO);
            }
            for (size_t j = 0; j < n - 1; j++)
            {
                close(pipes[j][0]);
                close(pipes[j][1]);
            }
            cmd->command_funct(cmd, env);
            exit(0);
        }
        else
        {
            pids[i] = pid;
        }
        i++;
    }
    for (size_t j = 0; j < n - 1; j++)
    {
        close(pipes[j][0]);
        close(pipes[j][1]);
    }
    for (size_t j = 0; j < i; j++)
        waitpid(pids[j], NULL, 0);
    free(pids);
    if (pipes)
        free(pipes);
}
References cd_execute(), s_command::command_funct, export_execute(), iter_next(), iter_start(), s_gen_list::size, and unset_execute().
Referenced by main().
export_execute()
void export_execute (t_command * command, t_gen_list * envioroment)
Definition at line 143 of file command_functs.c.
{
    t_node *current_node;
    char **new_variable;
    if (!command || !command->args || !envioroment)
        return;
    current_node = command->args->head->next;
    if (!current_node || !current_node->value)
        return;
    new_variable = ft_split2(current_node->value, '=');
    if (!new_variable || !new_variable[0] || !new_variable[1])
        return;
    env_set(envioroment, new_variable[0], new_variable[1]);
    size_t i = 0;
    while (i < 2)
    {
        free(new_variable[i]);
        i++;
    }
    free(new_variable);
}
References s_command::args, env_set(), ft_split2(), s_gen_list::head, s_node::next, and s_node::value.
Referenced by execute_commands_with_pipes(), and get_command_function().
init_command()
t_command * init_command (t_gen_list * args, t_command_funct funct, t_gen_list * redirects)
Definition at line 9 of file command.c.
{
    t_command   *new_command;
    new_command = ft_calloc(1, sizeof(t_command));
    new_command->args = args;
    new_command->command_funct = funct;
    new_command->redirects = redirects;
    return (new_command);
}
References s_command::args, s_command::command_funct, ft_calloc(), and s_command::redirects.
Referenced by parse_tokens_to_commands().
pwd_execute()
void pwd_execute (t_command * command, t_gen_list * envioroment)
Definition at line 115 of file command_functs.c.
{
    char *current_dir;
    if (command == NULL)
        return ;
    current_dir = env_get(envioroment, "PWD");
    printf("%s\n", current_dir);
    free(current_dir);
    exit(0);
}
References env_get().
Referenced by get_command_function().
unset_execute()
void unset_execute (t_command * command, t_gen_list * envioroment)
Definition at line 167 of file command_functs.c.
{
    t_node  *current_node;
    current_node = command->args->head->next;
    env_unset(envioroment, (char *)current_node->value);
}
References s_command::args, env_unset(), s_gen_list::head, s_node::next, and s_node::value.
Referenced by execute_commands_with_pipes(), and get_command_function().