Kyle's Doxygen Test: src/environment/environment_query.c File Reference
environment_query.c File Reference
#include "environment_internal.h"
Functions
bool env_has (t_gen_list *environment_vars, char *name)
Check if an environment variable exists by name.
char * env_get (t_gen_list *environment_vars, char *name)
Get the value of an environment variable by name.
Function Documentation
env_get()
char * env_get (t_gen_list * env, char * name)
Get the value of an environment variable by name.
The returned value is a newly allocated copy and must be freed by the caller.
Parameters
env Environment variable list.
name Name of the variable to search.
Returns
Dynamically allocated copy of the value, or NULL if not found.
See also
env_set
env_unset
env_has
t_env_var
Definition at line 20 of file environment_query.c.
{
    t_env_var   *found_var;
    found_var = find_in_list_ctx(environment_vars, var_name_filter, name);
    if (!found_var)
        return (NULL);
    return (ft_strdup(found_var->var_value));
}
References find_in_list_ctx(), ft_strdup(), var_name_filter(), and s_env_var::var_value.
Referenced by cd_execute(), pwd_execute(), and username().
env_has()
bool env_has (t_gen_list * env, char * name)
Check if an environment variable exists by name.
Parameters
env Environment variable list.
name Name of the variable.
Returns
true if the variable exists, false otherwise.
See also
env_set
env_unset
env_get
t_env_var
Definition at line 15 of file environment_query.c.
{
    return (contains_in_list_ctx(environment_vars, var_name_filter, name));
}
References contains_in_list_ctx(), and var_name_filter().