Kyle's Doxygen Test: src/environment/environment_serialization_deserialization.c File Reference
environment_serialization_deserialization.c File Reference
#include "environment_internal.h"
Functions
static char * env_var_to_string (void *element)
char ** env_serialize (t_gen_list *envioroment)
Serialize environment variables into a null-terminated string array.
t_gen_list * env_deserialize (char **str_array)
Convert a string array into an environment variable list.
Function Documentation
env_deserialize()
t_gen_list * env_deserialize (char ** str_array)
Convert a string array into an environment variable list.
Each string must follow the "NAME=VALUE" format.
Parameters
str_array Null-terminated array of strings.
Returns
Pointer to a newly allocated environment variable list, or NULL on error.
See also
env_serialize
t_env_var
Definition at line 39 of file environment_serialization_deserialization.c.
{
    int         i;
    size_t      j;
    t_gen_list  *env_var_list;
    char        **var_str_name_value_split;
    i = 0;
    env_var_list = init_list();
    while (str_array[i])
    {
        var_str_name_value_split = ft_split(str_array[i], '=');
        push_end(env_var_list, init_environment_var(var_str_name_value_split[0],
                var_str_name_value_split[1]));
        free(var_str_name_value_split);
        i++;
    }
    return (env_var_list);
}
References ft_split(), init_environment_var(), init_list(), and push_end().
Referenced by main().
env_serialize()
char ** env_serialize (t_gen_list * env)
Serialize environment variables into a null-terminated string array.
Each environment variable is represented as "NAME=VALUE".
Parameters
env Environment variable list.
Returns
Dynamically allocated null-terminated array of strings, or NULL on allocation failure.
See also
env_deserialize
t_env_var
Definition at line 32 of file environment_serialization_deserialization.c.
{
    if (!envioroment)
        return (NULL);
    return (serialize_to_string_array(envioroment, env_var_to_string));
}
References env_var_to_string(), and serialize_to_string_array().
Referenced by bin_execute(), and env_execute().
env_var_to_string()
static char * env_var_to_string (void * element) static
Definition at line 15 of file environment_serialization_deserialization.c.
{
    t_env_var   *env_var;
    char        *name_eq;
    char        *result;
    env_var = (t_env_var *)element;
    if (!env_var)
        return (NULL);
    name_eq = ft_strjoin(env_var->var_name, "=");
    if (!name_eq)
        return (NULL);
    result = ft_strjoin(name_eq, env_var->var_value);
    free(name_eq);
    return (result);
}
References ft_strjoin(), s_env_var::var_name, and s_env_var::var_value.
Referenced by env_serialize().