Kyle's Doxygen Test: src/environment/environment_internal.h File Reference
environment_internal.h File Reference
#include "../../include/environment.h"
#include "../../libft/libft.h"
#include <stdlib.h>
Classes
struct s_env_var
Represents a single environment variable (internal use).
Functions
t_env_var * init_environment_var (char *name, char *value)
Create a new environment variable.
void destroy_environment_var (void *env_var)
Destroy a single environment variable.
bool var_name_filter (void *var_ptr, void *context)
Filter function for comparing variable names.
Function Documentation
destroy_environment_var()
void destroy_environment_var (void * env_var)
Destroy a single environment variable.
Frees the name, value, and the structure itself. Designed to be compatible with generic list destruction functions.
Parameters
env_var Pointer to the environment variable to destroy.
See also
init_environment_var
Definition at line 44 of file envioroment_internal.c.
{
    t_env_var   *aux;
    aux = (t_env_var *)envioroment_var;
    free(aux->var_name);
    free(aux->var_value);
    free(aux);
}
References s_env_var::var_name, and s_env_var::var_value.
Referenced by env_destroy(), and env_unset().
init_environment_var()
t_env_var * init_environment_var (char * name, char * value)
Create a new environment variable.
Allocates and initializes a new t_env_var with the given name and value.
Parameters
name Name of the variable (must not be NULL).
value Value of the variable (can be NULL for empty).
Returns
Pointer to the newly allocated t_env_var, or NULL on allocation failure.
See also
destroy_environment_var
Definition at line 32 of file envioroment_internal.c.
{
    t_env_var   *new_env;
    new_env = ft_calloc(1, sizeof(t_env_var));
    if (new_env == NULL)
        return (NULL);
    new_env->var_name = name;
    new_env->var_value = value;
    return (new_env);
}
References ft_calloc(), s_env_var::var_name, and s_env_var::var_value.
Referenced by env_deserialize(), and env_set().
var_name_filter()
bool var_name_filter (void * var_ptr, void * context)
Filter function for comparing variable names.
Can be used as a callback in list search or remove operations.
Parameters
var_ptr Pointer to t_env_var.
context Pointer to a string with the variable name to match.
Returns
true if names match, false otherwise.
See also
t_env_var
Definition at line 17 of file envioroment_internal.c.
{
    char        *name;
    t_env_var   *var;
    size_t      name_size;
    name = (char *)context;
    var = (t_env_var *)var_ptr;
    name_size = ft_strlen(name);
    if (ft_strlen(var->var_name) == name_size && ft_strncmp(var->var_name, name,
            name_size) == 0)
        return (true);
    return (false);
}
References ft_strlen(), ft_strncmp(), and s_env_var::var_name.
Referenced by env_get(), env_has(), env_set(), and env_unset().