Kyle's Doxygen Test: src/environment/environment_operations.c File Reference
environment_operations.c File Reference
#include "environment_internal.h"
Functions
int env_set (t_gen_list *env, char *name, char *value)
Add or update an environment variable.
void env_unset (t_gen_list *envioroment, char *name)
Remove an environment variable by name.
void env_destroy (t_gen_list *env)
Destroy the entire environment list and free resources.
Function Documentation
env_destroy()
void env_destroy (t_gen_list * env)
Destroy the entire environment list and free resources.
Frees all variables, their names and values, then frees the list itself.
Parameters
env Environment variable list.
See also
env_set
env_unset
t_env_var
Definition at line 44 of file environment_operations.c.
{
    destroy_gen_list(env, destroy_environment_var);
}
References destroy_environment_var(), and destroy_gen_list().
Referenced by main().
env_set()
int env_set (t_gen_list * env, char * name, char * value)
Add or update an environment variable.
If the variable does not exist, it is created and added to the list. If the variable already exists, its value is updated.
Parameters
env Environment variable list.
name Name of the variable (must not be NULL).
value Value of the variable (can be NULL for empty).
Returns
1 on success, or an error code otherwise.
See also
env_unset
env_get
env_has
t_env_var
Definition at line 15 of file environment_operations.c.
{
    t_env_var   *new_var;
    t_env_var   *found_var;
    char        *previous_val;
    found_var = (t_env_var *)find_in_list_ctx(env, var_name_filter, name);
    if (found_var)
    {
        previous_val = found_var->var_value;
        found_var->var_value = ft_strdup(value);
        if (!found_var->var_value)
            return (0);
        free(previous_val);
        return (1);
    }
    new_var = init_environment_var(ft_strdup(name), ft_strdup(value));
    if (!new_var)
        return (0);
    push_front(env, (void *)new_var);
    return (1);
}
References find_in_list_ctx(), ft_strdup(), init_environment_var(), push_front(), var_name_filter(), and s_env_var::var_value.
Referenced by cd_execute(), and export_execute().
env_unset()
void env_unset (t_gen_list * env, char * name)
Remove an environment variable by name.
If the variable is found, it is removed from the list.
Parameters
env Environment variable list.
name Name of the variable to remove.
See also
env_set
env_get
env_has
t_env_var
Definition at line 38 of file environment_operations.c.
{
    remove_if_ctx(envioroment, var_name_filter, (void *)name,
        destroy_environment_var);
}
References destroy_environment_var(), remove_if_ctx(), and var_name_filter().
Referenced by unset_execute().