Kyle's Doxygen Test: include/environment.h File Reference
environment.h File Reference
#include "../list/list.h"
#include <stdbool.h>
Typedefs
typedef struct s_env_var t_env_var
Represents a single environment variable.
Functions
int env_set (t_gen_list *env, char *name, char *value)
Add or update an environment variable.
void env_unset (t_gen_list *env, char *name)
Remove an environment variable by name.
void env_destroy (t_gen_list *env)
Destroy the entire environment list and free resources.
char ** env_serialize (t_gen_list *env)
Serialize environment variables into a null-terminated string array.
t_gen_list * env_deserialize (char **str_array)
Convert a string array into an environment variable list.
char * env_get (t_gen_list *env, char *name)
Get the value of an environment variable by name.
bool env_has (t_gen_list *env, char *name)
Check if an environment variable exists by name.
Typedef Documentation
t_env_var
typedef struct s_env_var t_env_var
Represents a single environment variable.
Each environment variable consists of a name and its associated value.
Definition at line 29 of file environment.h.
Function Documentation
env_deserialize()
t_gen_list * env_deserialize (char ** str_array)
Convert a string array into an environment variable list.
Each string must follow the "NAME=VALUE" format.
Parameters
str_array Null-terminated array of strings.
Returns
Pointer to a newly allocated environment variable list, or NULL on error.
See also
env_serialize
t_env_var
Definition at line 39 of file environment_serialization_deserialization.c.
{
    int         i;
    size_t      j;
    t_gen_list  *env_var_list;
    char        **var_str_name_value_split;
    i = 0;
    env_var_list = init_list();
    while (str_array[i])
    {
        var_str_name_value_split = ft_split(str_array[i], '=');
        push_end(env_var_list, init_environment_var(var_str_name_value_split[0],
                var_str_name_value_split[1]));
        free(var_str_name_value_split);
        i++;
    }
    return (env_var_list);
}
References ft_split(), init_environment_var(), init_list(), and push_end().
Referenced by main().
env_destroy()
void env_destroy (t_gen_list * env)
Destroy the entire environment list and free resources.
Frees all variables, their names and values, then frees the list itself.
Parameters
env Environment variable list.
See also
env_set
env_unset
t_env_var
Definition at line 44 of file environment_operations.c.
{
    destroy_gen_list(env, destroy_environment_var);
}
References destroy_environment_var(), and destroy_gen_list().
Referenced by main().
env_get()
char * env_get (t_gen_list * env, char * name)
Get the value of an environment variable by name.
The returned value is a newly allocated copy and must be freed by the caller.
Parameters
env Environment variable list.
name Name of the variable to search.
Returns
Dynamically allocated copy of the value, or NULL if not found.
See also
env_set
env_unset
env_has
t_env_var
Definition at line 20 of file environment_query.c.
{
    t_env_var   *found_var;
    found_var = find_in_list_ctx(environment_vars, var_name_filter, name);
    if (!found_var)
        return (NULL);
    return (ft_strdup(found_var->var_value));
}
References find_in_list_ctx(), ft_strdup(), var_name_filter(), and s_env_var::var_value.
Referenced by cd_execute(), pwd_execute(), and username().
env_has()
bool env_has (t_gen_list * env, char * name)
Check if an environment variable exists by name.
Parameters
env Environment variable list.
name Name of the variable.
Returns
true if the variable exists, false otherwise.
See also
env_set
env_unset
env_get
t_env_var
Definition at line 15 of file environment_query.c.
{
    return (contains_in_list_ctx(environment_vars, var_name_filter, name));
}
References contains_in_list_ctx(), and var_name_filter().
env_serialize()
char ** env_serialize (t_gen_list * env)
Serialize environment variables into a null-terminated string array.
Each environment variable is represented as "NAME=VALUE".
Parameters
env Environment variable list.
Returns
Dynamically allocated null-terminated array of strings, or NULL on allocation failure.
See also
env_deserialize
t_env_var
Definition at line 32 of file environment_serialization_deserialization.c.
{
    if (!envioroment)
        return (NULL);
    return (serialize_to_string_array(envioroment, env_var_to_string));
}
References env_var_to_string(), and serialize_to_string_array().
Referenced by bin_execute(), and env_execute().
env_set()
int env_set (t_gen_list * env, char * name, char * value)
Add or update an environment variable.
If the variable does not exist, it is created and added to the list. If the variable already exists, its value is updated.
Parameters
env Environment variable list.
name Name of the variable (must not be NULL).
value Value of the variable (can be NULL for empty).
Returns
1 on success, or an error code otherwise.
See also
env_unset
env_get
env_has
t_env_var
Definition at line 15 of file environment_operations.c.
{
    t_env_var   *new_var;
    t_env_var   *found_var;
    char        *previous_val;
    found_var = (t_env_var *)find_in_list_ctx(env, var_name_filter, name);
    if (found_var)
    {
        previous_val = found_var->var_value;
        found_var->var_value = ft_strdup(value);
        if (!found_var->var_value)
            return (0);
        free(previous_val);
        return (1);
    }
    new_var = init_environment_var(ft_strdup(name), ft_strdup(value));
    if (!new_var)
        return (0);
    push_front(env, (void *)new_var);
    return (1);
}
References find_in_list_ctx(), ft_strdup(), init_environment_var(), push_front(), var_name_filter(), and s_env_var::var_value.
Referenced by cd_execute(), and export_execute().
env_unset()
void env_unset (t_gen_list * env, char * name)
Remove an environment variable by name.
If the variable is found, it is removed from the list.
Parameters
env Environment variable list.
name Name of the variable to remove.
See also
env_set
env_get
env_has
t_env_var
Definition at line 38 of file environment_operations.c.
{
    remove_if_ctx(envioroment, var_name_filter, (void *)name,
        destroy_environment_var);
}
References destroy_environment_var(), remove_if_ctx(), and var_name_filter().
Referenced by unset_execute().