Kyle's Doxygen Test: src/find_command.c File Reference
find_command.c File Reference
#include "../include/bin_commandss_execution.h"
#include "../libft/libft.h"
#include "unistd.h"
Functions
static char * get_final_path (char *path, char *cmd)
static char * checker_path (char *env, char *cmd)
char * find_command (char **env, char *cmd)
Function Documentation
checker_path()
static char * checker_path (char * env, char * cmd) static
Definition at line 28 of file find_command.c.
{
    if (!env && access(cmd, X_OK) != 0)
    {
        write(2, "Path doest find\n", 17);
        exit(1);
    }
    else if (access(cmd, X_OK) == 0)
        return (cmd);
    return (NULL);
}
Referenced by find_command().
find_command()
char * find_command (char ** env, char * cmd)
Definition at line 40 of file find_command.c.
{
    int     y;
    char    **path;
    char    *final_path;
    y = 0;
    while (env[y] && ft_strncmp(env[y], "PATH=", 5) != 0)
        y++;
    if (checker_path(env[y], cmd))
        return (checker_path(env[y], cmd));
    path = ft_split(env[y] + 5, ':');
    y = 0;
    while (path[y])
    {
        final_path = get_final_path(path[y], cmd);
        if (access(final_path, X_OK) == 0)
        {
            free_double_pointer(path);
            return (final_path);
        }
        free(final_path);
        y++;
    }
    free_double_pointer(path);
    return (NULL);
}
References checker_path(), free_double_pointer(), ft_split(), ft_strncmp(), and get_final_path().
Referenced by bin_execute().
get_final_path()
static char * get_final_path (char * path, char * cmd) static
Definition at line 17 of file find_command.c.
{
    char    *aux;
    char    *result;
    aux = ft_strjoin(path, "/");
    result = ft_strjoin(aux, cmd);
    free(aux);
    return (result);
}
References ft_strjoin().
Referenced by find_command().