Kyle's Doxygen Test: libft/ft_puthexnum.c File Reference
ft_puthexnum.c File Reference
#include "libft.h"
Functions
static int ft_pos (unsigned int pf)
static void ft_six (unsigned int pf, char *p3, int i)
int ft_puthexnum (unsigned int pf)
Function Documentation
ft_pos()
static int ft_pos (unsigned int pf) static
Definition at line 15 of file ft_puthexnum.c.
{
    int i;
    i = 0;
    while (pf > 0)
    {
        pf = pf / 16;
        i++;
    }
    return (i + 1);
}
Referenced by ft_puthexnum().
ft_puthexnum()
int ft_puthexnum (unsigned int pf)
Definition at line 51 of file ft_puthexnum.c.
{
    int     i;
    char    *p3;
    if (pf == 0)
        return (ft_putchar('0'));
    i = ft_pos(pf);
    p3 = malloc(ft_pos(pf));
    if (!p3)
        return ('\0');
    ft_six(pf, p3, i - 1);
    free(p3);
    return (i - 1);
}
References ft_pos(), ft_putchar(), and ft_six().
Referenced by ft_selector().
ft_six()
static void ft_six (unsigned int pf, char * p3, int i) static
Definition at line 28 of file ft_puthexnum.c.
{
    p3[i] = '\0';
    i--;
    while (pf >= 16 && i > 0)
    {
        if ((pf % 16 <= 9))
            p3[i] = pf % 16 + '0';
        else
            p3[i] = pf % 16 + 'a' - 10;
        pf = pf / 16;
        i--;
    }
    if ((pf % 16 <= 9))
    {
        p3[i] = pf % 16 + '0';
        i--;
    }
    if (pf % 16 >= 10)
        p3[i] = pf % 16 + 'a' - 10;
    ft_putstr(p3);
}
References ft_putstr().
Referenced by ft_puthexnum().