Kyle's Doxygen Test: libft/ft_split.c File Reference
ft_split.c File Reference
#include "libft.h"
Functions
static size_t ft_extractor (char const *n, size_t k, size_t s, char t)
static char * ft_survivor (char const *n, size_t k, size_t s, char t)
static size_t ft_worldette (const char *s, char c)
static char ** ft_rapt (char const *s, char c, char **p3, size_t p)
char ** ft_split (char const *s, char c)
Function Documentation
ft_extractor()
static size_t ft_extractor (char const * n, size_t k, size_t s, char t) static
Definition at line 15 of file ft_split.c.
{
    size_t  j;
    j = 0;
    while (s < k)
    {
        if (n[s] == t)
            j++;
        s++;
    }
    return (j - 1);
}
Referenced by ft_survivor().
ft_rapt()
static char ** ft_rapt (char const * s, char c, char ** p3, size_t p) static
Definition at line 76 of file ft_split.c.
{
    size_t  r;
    size_t  n;
    r = -1;
    n = 0;
    while (s[p])
    {
        p++;
        if (s[p] == c || s[p] == '\0')
        {
            if (s[p - 1] != c)
            {
                p3[++r] = ft_survivor(s, p, n, c);
                if (!p3[r])
                {
                    while (r != 0)
                        free(p3[r-- - 1]);
                    free(p3);
                    return (NULL);
                }
                n = p;
            }
        }
    }
    return (p3);
}
References ft_survivor().
Referenced by ft_split().
ft_split()
char ** ft_split (char const * s, char c)
Definition at line 105 of file ft_split.c.
{
    char    **p3;
    size_t  p;
    p3 = NULL;
    p = 0;
    if (!s)
        return (NULL);
    p3 = (char **)ft_calloc((ft_worldette(s, c) + 1), sizeof(char *));
    if (!p3)
        return (NULL);
    return (ft_rapt(s, c, p3, p));
}
References ft_calloc(), ft_rapt(), and ft_worldette().
Referenced by env_deserialize(), and find_command().
ft_survivor()
static char * ft_survivor (char const * n, size_t k, size_t s, char t) static
Definition at line 29 of file ft_split.c.
{
    char    *p2;
    char    *p1;
    size_t  i;
    size_t  p;
    i = 0;
    p2 = NULL;
    p1 = (char *)n;
    p = ft_extractor(n, k, s, t);
    p2 = malloc(k - s - p);
    if (!p2)
        return (NULL);
    while (s < k)
    {
        while (p1[s] == t)
            s++;
        p2[i] = p1[s];
        s++;
        i++;
    }
    p2[i] = '\0';
    return (p2);
}
References ft_extractor().
Referenced by ft_rapt().
ft_worldette()
static size_t ft_worldette (const char * s, char c) static
Definition at line 55 of file ft_split.c.
{
    size_t  count;
    size_t  i;
    count = 0;
    i = 0;
    while (s[i])
    {
        while (s[i] == c)
            i++;
        if (s[i])
        {
            count++;
            while (s[i] && s[i] != c)
                i++;
        }
    }
    return (count);
}
Referenced by ft_split().