Kyle's Doxygen Test: libft/ft_calloc.c File Reference
ft_calloc.c File Reference
#include "libft.h"
Functions
void * ft_calloc (size_t nmemb, size_t size)
Function Documentation
ft_calloc()
void * ft_calloc (size_t nmemb, size_t size)
Definition at line 15 of file ft_calloc.c.
{
    char    *p1;
    size_t  s;
    size_t  i;
    s = 0;
    i = 0;
    s = nmemb * size;
    if (s >= 16711568 || s <= 0)
        return (NULL);
    p1 = malloc(s + 1);
    if (!p1)
        return (NULL);
    while (i <= s)
    {
        p1[i] = 0;
        i++;
    }
    return (p1);
}
Referenced by ft_split(), ft_split2(), ft_substr(), init_command(), and init_environment_var().