Kyle's Doxygen Test: libft/ft_putunmath.c File Reference
ft_putunmath.c File Reference
#include "libft.h"
Functions
static int ft_count (unsigned int i)
static void ft_writenub (unsigned int i)
int ft_putunmath (unsigned int i)
Function Documentation
ft_count()
static int ft_count (unsigned int i) static
Definition at line 15 of file ft_putunmath.c.
{
    int n;
    n = 0;
    while (i > 9)
    {
        i = i / 10;
        n++;
    }
    return (n + 1);
}
Referenced by ft_putunmath().
ft_putunmath()
int ft_putunmath (unsigned int i)
Definition at line 35 of file ft_putunmath.c.
{
    ft_writenub(i);
    return (ft_count(i));
}
References ft_count(), and ft_writenub().
Referenced by ft_selector().
ft_writenub()
static void ft_writenub (unsigned int i) static
Definition at line 28 of file ft_putunmath.c.
{
    if (i > 9)
        ft_writenub(i / 10);
    ft_putchar(i % 10 + '0');
}
References ft_putchar(), and ft_writenub().
Referenced by ft_putunmath(), and ft_writenub().