Kyle's Doxygen Test: libft/ft_strjoin.c File Reference
ft_strjoin.c File Reference
#include "libft.h"
Functions
static char * ft_cpi (char *p2, char const *s1, char const *s2)
char * ft_strjoin (char const *s1, char const *s2)
Function Documentation
ft_cpi()
static char * ft_cpi (char * p2, char const * s1, char const * s2) static
Definition at line 15 of file ft_strjoin.c.
{
    size_t  i;
    size_t  t;
    t = 0;
    i = 0;
    while (s1 && s1[i])
    {
        p2[i] = s1[i];
        i++;
    }
    while (s2 && s2[t])
    {
        p2[i] = s2[t];
        i++;
        t++;
    }
    p2[i] = '\0';
    return (p2);
}
Referenced by ft_strjoin().
ft_strjoin()
char * ft_strjoin (char const * s1, char const * s2)
Definition at line 37 of file ft_strjoin.c.
{
    size_t  j;
    size_t  s;
    char    *p1;
    j = ft_strlen(s1);
    s = ft_strlen(s2);
    p1 = malloc(j + s + 1);
    if (!p1)
        return (NULL);
    return (ft_cpi(p1, s1, s2));
}
References ft_cpi(), and ft_strlen().
Referenced by cd_execute(), env_var_to_string(), get_final_path(), and username().