Kyle's Doxygen Test: libft/ft_strlen.c File Reference
ft_strlen.c File Reference
#include "libft.h"
Functions
size_t ft_strlen (const char *str)
Function Documentation
ft_strlen()
size_t ft_strlen (const char * str)
Definition at line 15 of file ft_strlen.c.
{
    size_t  i;
    if (!str)
        return (0);
    i = 0;
    while (str[i] != '\0')
    {
        i++;
    }
    return (i);
}
Referenced by echo_execute(), ft_ssubstr(), ft_strdup(), ft_strjoin(), ft_strlcat(), ft_strlcpy(), ft_strmapi(), ft_strtrim(), ft_substr(), get_command_function(), get_next_argument(), get_redirects_from_str_arr(), history_checker(), init_redirect(), main(), parse_tokens_to_commands(), special_char(), tokenize(), and var_name_filter().