Kyle's Doxygen Test: libft/ft_printf.c File Reference
ft_printf.c File Reference
#include "libft.h"
Functions
int ft_printf (char const *str,...)
Function Documentation
ft_printf()
int ft_printf (char const * str, ...)
Definition at line 15 of file ft_printf.c.
{
    va_list pf;
    size_t  t;
    t = 0;
    va_start(pf, str);
    while (*str)
    {
        if (*str == '%')
        {
            str++;
            t += ft_selector(pf, str);
        }
        else
            t += ft_putchar(*str);
        str++;
    }
    va_end(pf);
    return (t);
}
References ft_putchar(), and ft_selector().
Referenced by echo_execute().