Kyle's Doxygen Test: libft/ft_selector.c File Reference
ft_selector.c File Reference
#include "libft.h"
Functions
int ft_selector (va_list pf, char const *str)
Function Documentation
ft_selector()
int ft_selector (va_list pf, char const * str)
Definition at line 15 of file ft_selector.c.
{
    if (*str == 'c')
        return (ft_putchar(va_arg(pf, int)));
    if (*str == 's')
        return (ft_putstr(va_arg(pf, char *)));
    if (*str == 'X')
        return (ft_puthexnumax(va_arg(pf, unsigned long)));
    if (*str == 'x')
        return (ft_puthexnum(va_arg(pf, unsigned long)));
    if (*str == 'd' || *str == 'i')
        return (ft_putnb(va_arg(pf, int)));
    if (*str == 'p')
        return (ft_putpointer(va_arg(pf, void *)));
    if (*str == 'u')
        return (ft_putunmath(va_arg(pf, unsigned int)));
    if (*str == '%')
        return (ft_putchar('%'));
    return ('\0');
}
References ft_putchar(), ft_puthexnum(), ft_puthexnumax(), ft_putnb(), ft_putpointer(), ft_putstr(), and ft_putunmath().
Referenced by ft_printf().