Kyle's Doxygen Test: libft/ft_putchar.c File Reference
ft_putchar.c File Reference
#include "libft.h"
Functions
int ft_putchar (int pf)
Function Documentation
ft_putchar()
int ft_putchar (int pf)
Definition at line 15 of file ft_putchar.c.
{
    write(1, &pf, 1);
    return (1);
}
Referenced by ft_printf(), ft_puthexnum(), ft_puthexnumax(), ft_putstr(), ft_selector(), ft_trueputnb(), and ft_writenub().