Kyle's Doxygen Test: libft/ft_putnbr_fd.c File Reference
ft_putnbr_fd.c File Reference
#include "libft.h"
Functions
void ft_putnbr_fd (int n, int fd)
Function Documentation
ft_putnbr_fd()
void ft_putnbr_fd (int n, int fd)
Definition at line 15 of file ft_putnbr_fd.c.
{
    if (n == -2147483648)
        ft_putstr_fd("-2147483648", fd);
    else
    {
        if (n < 0)
        {
            n = -n;
            ft_putchar_fd('-', fd);
        }
        if (n > 9)
            ft_putnbr_fd(n / 10, fd);
        ft_putchar_fd(n % 10 + '0', fd);
    }
}
References ft_putchar_fd(), ft_putnbr_fd(), and ft_putstr_fd().
Referenced by ft_putnbr_fd().