Kyle's Doxygen Test: libft/ft_putnb.c File Reference
ft_putnb.c File Reference
#include "libft.h"
Functions
static int ft_count (int i)
static void ft_trueputnb (int i)
int ft_putnb (int i)
Function Documentation
ft_count()
static int ft_count (int i) static
Definition at line 15 of file ft_putnb.c.
{
    int n;
    n = 0;
    if (i < 0)
        n++;
    while (i < -9 || i > 9)
    {
        i = i / 10;
        n++;
    }
    return (n + 1);
}
Referenced by ft_putnb().
ft_putnb()
int ft_putnb (int i)
Definition at line 47 of file ft_putnb.c.
{
    ft_trueputnb(i);
    return (ft_count(i));
}
References ft_count(), and ft_trueputnb().
Referenced by ft_selector(), and ft_trueputnb().
ft_trueputnb()
static void ft_trueputnb (int i) static
Definition at line 30 of file ft_putnb.c.
{
    if (i == -2147483648)
        ft_putstr("-2147483648");
    else
    {
        if (i < 0)
        {
            i = -i;
            ft_putchar('-');
        }
        if (i > 9)
            ft_putnb(i / 10);
        ft_putchar(i % 10 + '0');
    }
}
References ft_putchar(), ft_putnb(), and ft_putstr().
Referenced by ft_putnb().