Kyle's Doxygen Test: libft/ft_puthexnumax.c File Reference
ft_puthexnumax.c File Reference
#include "libft.h"
Functions
static void ft_puthex (unsigned int pf, char *p3, int i)
static int ft_pos (unsigned int pf)
int ft_puthexnumax (unsigned int pf)
Function Documentation
ft_pos()
static int ft_pos (unsigned int pf) static
Definition at line 38 of file ft_puthexnumax.c.
{
    int i;
    i = 0;
    while (pf > 0)
    {
        pf = pf / 16;
        i++;
    }
    return (i);
}
Referenced by ft_puthexnumax().
ft_puthex()
static void ft_puthex (unsigned int pf, char * p3, int i) static
Definition at line 15 of file ft_puthexnumax.c.
{
    p3[i] = '\0';
    i--;
    while (pf >= 16)
    {
        if (pf % 16 <= 9)
            p3[i] = pf % 16 + '0';
        else
            p3[i] = pf % 16 + 'A' - 10;
        pf = pf / 16;
        i--;
    }
    if ((pf % 16) <= 9)
    {
        p3[i] = pf % 16 + '0';
        i--;
    }
    if (pf % 16 >= 10)
        p3[i] = pf % 16 + 'A' - 10;
    ft_putstr(p3);
}
References ft_putstr().
Referenced by ft_puthexnumax().
ft_puthexnumax()
int ft_puthexnumax (unsigned int pf)
Definition at line 51 of file ft_puthexnumax.c.
{
    int     i;
    char    *p3;
    if (pf == 0)
        return (ft_putchar('0'));
    i = ft_pos(pf);
    p3 = malloc(ft_pos(pf) + 1);
    if (!p3)
    {
        free(p3);
        return ('\0');
    }
    ft_puthex(pf, p3, i);
    free(p3);
    return (i);
}
References ft_pos(), ft_putchar(), and ft_puthex().
Referenced by ft_selector().