Kyle's Doxygen Test: libft/ft_strdup.c File Reference
ft_strdup.c File Reference
#include "libft.h"
Functions
static char * ft_strcpy (char *str, char *dest)
char * ft_strdup (const char *s)
Function Documentation
ft_strcpy()
static char * ft_strcpy (char * str, char * dest) static
Definition at line 15 of file ft_strdup.c.
{
    int i;
    i = 0;
    while (str[i])
    {
        dest[i] = str[i];
        i++;
    }
    dest[i] = '\0';
    return (dest);
}
Referenced by ft_strdup().
ft_strdup()
char * ft_strdup (const char * s)
Definition at line 29 of file ft_strdup.c.
{
    char    *p1;
    p1 = malloc(ft_strlen(s) + 1);
    if (!p1)
        return (NULL);
    ft_strcpy((char *)s, p1);
    return (p1);
}
References ft_strcpy(), and ft_strlen().
Referenced by cd_execute(), env_get(), env_set(), ft_itoa(), serialize_arg(), and username().