Kyle's Doxygen Test: libft/ft_itoa.c File Reference
ft_itoa.c File Reference
#include "libft.h"
Functions
static char * ft_putnbr (int n, int pos, char *p3, char nb)
static int ft_div (int n)
static int ft_isnegative (int n)
char * ft_itoa (int n)
Function Documentation
ft_div()
static int ft_div (int n) static
Definition at line 33 of file ft_itoa.c.
{
    int ps;
    ps = 1;
    while (9 < n || -9 > n)
    {
        n = n / 10;
        ps++;
    }
    return (ps);
}
Referenced by ft_itoa().
ft_isnegative()
static int ft_isnegative (int n) static
Definition at line 46 of file ft_itoa.c.
{
    if (n < 0)
        return (1);
    else
        return (0);
}
Referenced by ft_itoa().
ft_itoa()
char * ft_itoa (int n)
Definition at line 54 of file ft_itoa.c.
{
    char    *p3;
    int     ps;
    char    nb;
    nb = '+';
    if (n == 2147483647)
        return (ft_strdup("2147483647"));
    if (n == -2147483648)
        return (ft_strdup("-2147483648"));
    ps = ft_div(n);
    p3 = (char *)malloc(ft_isnegative(n) + ps + 1);
    if (!p3)
        return (NULL);
    if (n < 0)
    {
        n = -n;
        nb = '-';
    }
    ft_putnbr(n, ps, p3, nb);
    if (nb == '-')
        p3[0] = nb;
    return (p3);
}
References ft_div(), ft_isnegative(), ft_putnbr(), and ft_strdup().
ft_putnbr()
static char * ft_putnbr (int n, int pos, char * p3, char nb) static
Definition at line 15 of file ft_itoa.c.
{
    int i;
    i = pos;
    if (nb == '-')
        i++;
    p3[i] = '\0';
    while (pos > 0)
    {
        i--;
        p3[i] = n % 10 + '0';
        n = n / 10;
        pos--;
    }
    return (p3);
}
Referenced by ft_itoa().