Kyle's Doxygen Test: libft/ft_strncmp.c File Reference
ft_strncmp.c File Reference
#include "libft.h"
Functions
int ft_strncmp (const char *s1, const char *s2, size_t n)
Function Documentation
ft_strncmp()
int ft_strncmp (const char * s1, const char * s2, size_t n)
Definition at line 15 of file ft_strncmp.c.
{
    unsigned int    i;
    unsigned char   *p3;
    unsigned char   *p2;
    if (!s1 || !s2 || n == 0)
        return (0);
    p3 = (unsigned char *)s1;
    p2 = (unsigned char *)s2;
    i = 0;
    if (!n)
        return (0);
    while ((size_t)i < n && (p3[i] || p2[i]))
    {
        if (p3[i] != p2[i])
            return (p3[i] - p2[i]);
        i++;
    }
    return (0);
}
Referenced by echo_execute(), find_command(), get_command_function(), get_next_argument(), get_redirection_type_from_str(), main(), special_char(), and var_name_filter().