Kyle's Doxygen Test: libft/ft_putstr.c File Reference
ft_putstr.c File Reference
#include "libft.h"
Functions
int ft_putstr (char *str)
Function Documentation
ft_putstr()
int ft_putstr (char * str)
Definition at line 15 of file ft_putstr.c.
{
    int i;
    i = 0;
    if (!str)
        return (ft_putstr("(null)"));
    while (str[i])
    {
        i += ft_putchar(str[i]);
    }
    return (i);
}
References ft_putchar(), and ft_putstr().
Referenced by ft_puthex(), ft_puthex(), ft_putpointer(), ft_putstr(), ft_selector(), ft_six(), and ft_trueputnb().