Kyle's Doxygen Test: libft/ft_putpointer.c File Reference
ft_putpointer.c File Reference
#include "libft.h"
Functions
static int ft_pos (unsigned long pf)
static void ft_puthex (unsigned long pf, char *p3, int i)
int ft_putpointer (void *pf)
Function Documentation
ft_pos()
static int ft_pos (unsigned long pf) static
Definition at line 15 of file ft_putpointer.c.
{
    int i;
    i = 0;
    while (pf > 0)
    {
        pf = pf / 16;
        i++;
    }
    return (i);
}
Referenced by ft_putpointer().
ft_puthex()
static void ft_puthex (unsigned long pf, char * p3, int i) static
Definition at line 28 of file ft_putpointer.c.
{
    p3[i] = '\0';
    i--;
    while (pf >= 16)
    {
        if (pf % 16 <= 9)
            p3[i] = pf % 16 + '0';
        else
            p3[i] = pf % 16 + 'a' - 10;
        pf = pf / 16;
        i--;
    }
    if (pf % 16 <= 9)
    {
        p3[i] = pf % 16 + '0';
        i--;
    }
    if (pf % 16 >= 10)
        p3[i] = pf % 16 + 'a' - 10;
    ft_putstr(p3);
}
References ft_putstr().
Referenced by ft_putpointer().
ft_putpointer()
int ft_putpointer (void * pf)
Definition at line 51 of file ft_putpointer.c.
{
    unsigned long   p2;
    int             i;
    char            *p3;
    if (!pf)
        return (ft_putstr("(nil)"));
    p2 = (unsigned long)pf;
    i = ft_pos(p2);
    p3 = (char *)malloc(ft_pos(p2) + 3);
    if (!p3)
    {
        free(p3);
        return ('\0');
    }
    p3[0] = '0';
    p3[1] = 'x';
    ft_puthex(p2, p3, i + 2);
    free(p3);
    return (i + 2);
}
References ft_pos(), ft_puthex(), and ft_putstr().
Referenced by ft_selector().