Kyle's Doxygen Test: libft/get_next_line_utils.c File Reference
get_next_line_utils.c File Reference
#include "libft.h"
Functions
int ft_sstrlen (char *ret)
char * ft_sstrchr (char *s, int j)
char * ft_sstrjoin (char *temp, char *s)
void * ft_caalloc (size_t nmemb, size_t size)
Function Documentation
ft_caalloc()
void * ft_caalloc (size_t nmemb, size_t size)
Definition at line 71 of file get_next_line_utils.c.
{
    char    *p1;
    size_t  s;
    size_t  i;
    i = 0;
    s = nmemb * size;
    if (s >= 16711568 || s <= 0)
        return (NULL);
    p1 = malloc(s + 1);
    if (!p1)
        return (NULL);
    while (i <= s)
    {
        p1[i] = 0;
        i++;
    }
    return (p1);
}
Referenced by ft_readme(), ft_sstrjoin(), ft_ssubnstr(), and ft_ssubstr().
ft_sstrchr()
char * ft_sstrchr (char * s, int j)
Definition at line 27 of file get_next_line_utils.c.
{
    int i;
    i = 0;
    if (s == NULL)
        return (NULL);
    while (s[i])
    {
        if (s[i] == (char)j)
            return (s + i);
        i++;
    }
    return (NULL);
}
Referenced by get_next_line().
ft_sstrjoin()
char * ft_sstrjoin (char * temp, char * s)
Definition at line 43 of file get_next_line_utils.c.
{
    int     i;
    int     j;
    char    *res;
    if (!s || !temp)
        return (NULL);
    res = NULL;
    j = 0;
    res = (char *)ft_caalloc(ft_sstrlen(s) + ft_sstrlen(temp), sizeof(char));
    if (!res)
        return (NULL);
    i = 0;
    while (temp[j])
    {
        res[j] = temp[j];
        j++;
    }
    while (s && s[i] && j < ft_sstrlen(s) + ft_sstrlen(temp))
    {
        res[j] = s[i];
        j++;
        i++;
    }
    return (free(s), free(temp), res);
}
References ft_caalloc(), and ft_sstrlen().
Referenced by ft_readme().
ft_sstrlen()
int ft_sstrlen (char * ret)
Definition at line 15 of file get_next_line_utils.c.
{
    int i;
    if (!ret)
        return (0);
    i = 0;
    while (ret[i])
        i++;
    return (i);
}
Referenced by ft_sstrjoin().