Kyle's Doxygen Test: libft/get_next_line.c File Reference
get_next_line.c File Reference
#include "libft.h"
Functions
char * ft_readme (int fd, char *fv)
char * ft_ssubstr (char *s)
char * ft_ssubnstr (char *s)
char * ft_extarct (char *fv)
char * get_next_line (int fd)
Function Documentation
ft_extarct()
char * ft_extarct (char * fv)
Definition at line 85 of file get_next_line.c.
{
    char    *ret;
    char    *p;
    ret = NULL;
    p = fv;
    if (!fv)
        return (NULL);
    while (*fv != '\n' && fv)
        fv++;
    fv++;
    ret = ft_ssubstr(fv);
    if (!ret)
        return (free(p), ret);
    return (free(p), ret);
}
References ft_ssubstr().
Referenced by get_next_line().
ft_readme()
char * ft_readme (int fd, char * fv)
Definition at line 15 of file get_next_line.c.
{
    char    *buffer;
    int     i;
    buffer = NULL;
    buffer = ft_caalloc(BUFFER_SIZE, sizeof(char));
    if (!buffer)
        return (free(fv), NULL);
    i = read(fd, buffer, BUFFER_SIZE);
    if (i < 0)
    {
        if (fv)
            free(fv);
        return (free(buffer), NULL);
    }
    if (i == 0)
        return (free(buffer), fv);
    if (fv)
    {
        buffer = ft_sstrjoin(fv, buffer);
        if (!buffer)
            return (free(fv), NULL);
    }
    return (buffer);
}
References BUFFER_SIZE, ft_caalloc(), and ft_sstrjoin().
Referenced by get_next_line().
ft_ssubnstr()
char * ft_ssubnstr (char * s)
Definition at line 63 of file get_next_line.c.
{
    int     i;
    char    *result;
    if (!s)
        return (NULL);
    i = 0;
    result = NULL;
    result = ft_caalloc(ft_strchr(s, '\n') - s + 1, sizeof(char));
    if (!result)
        return (NULL);
    result[i] = s[i];
    i++;
    while (s[i] && result[i - 1] != '\n')
    {
        result[i] = s[i];
        i++;
    }
    return (result);
}
References ft_caalloc(), and ft_strchr().
Referenced by get_next_line().
ft_ssubstr()
char * ft_ssubstr (char * s)
Definition at line 42 of file get_next_line.c.
{
    char    *result;
    int     i;
    result = NULL;
    i = 0;
    if (!s)
        return (NULL);
    result = ft_caalloc(ft_strlen(s), sizeof(char));
    if (!result)
        return (NULL);
    while (*s != '\0')
    {
        result[i] = *s;
        i++;
        s++;
    }
    return (result);
}
References ft_caalloc(), and ft_strlen().
Referenced by ft_extarct(), and get_next_line().
get_next_line()
char * get_next_line (int fd)
Definition at line 103 of file get_next_line.c.
{
    static char *fv = NULL;
    char        *ret;
    ret = fv;
    if (fd < 0 || BUFFER_SIZE <= 0 || FOPEN_MAX < fd)
        return (NULL);
    fv = ft_readme(fd, fv);
    if (!fv)
        return (NULL);
    if (fv && ft_sstrchr(fv, '\n'))
    {
        ret = ft_ssubnstr(fv);
        fv = ft_extarct(fv);
        return (ret);
    }
    if (fv && fv == ret)
    {
        ret = ft_ssubstr(fv);
        free(fv);
        fv = NULL;
        return (ret);
    }
    return (get_next_line(fd));
}
References BUFFER_SIZE, ft_extarct(), ft_readme(), ft_sstrchr(), ft_ssubnstr(), ft_ssubstr(), and get_next_line().
Referenced by get_next_line().