Kyle's Doxygen Test: libft/libft.h File Reference
libft.h File Reference
#include <fcntl.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
Classes
struct s_list
Macros
#define BUFFER_SIZE 100
Typedefs
typedef struct s_list t_list
Functions
t_list * ft_lstnew (void *content)
int ft_memcmp (const void *s1, const void *s2, size_t n)
void * ft_memchr (const void *s, int c, size_t n)
void * ft_memmove (void *dest, const void *src, size_t n)
void * ft_memcpy (void *dest, const void *src, size_t n)
char * ft_strchr (const char *s, int c)
size_t ft_strlcat (char *dst, const char *src, size_t size)
size_t ft_strlcpy (char *dst, const char *src, size_t size)
size_t ft_strlen (const char *str)
int ft_strncmp (const char *s1, const char *s2, size_t n)
char * ft_strnstr (const char *big, const char *little, size_t len)
char * ft_strrchr (const char *s, int c)
int ft_tolower (int c)
int ft_toupper (int c)
int ft_atoi (const char *nptr)
void ft_bzero (void *s, size_t n)
int ft_isalnum (int c)
int ft_isalpha (int c)
int ft_isascii (int c)
int ft_isdigit (int c)
int ft_isprint (int c)
void ft_striteri (char *s, void(*f)(unsigned int, char *))
void ft_putchar_fd (char c, int fd)
char * ft_strtrim (char const *s1, char const *set)
char * ft_itoa (int n)
void ft_putendl_fd (char *s, int fd)
char ** ft_split (char const *s, char c)
char * ft_strmapi (char const *s, char(*f)(unsigned int, char))
void * ft_memset (void *s, int c, size_t n)
char * ft_strdup (const char *s)
char * ft_strjoin (char const *s1, char const *s2)
char * ft_substr (char const *s, unsigned int start, size_t len)
void * ft_calloc (size_t nmemb, size_t size)
void ft_putnbr_fd (int n, int fd)
void ft_putstr_fd (char *s, int fd)
void ft_lstadd_front (t_list **lst, t_list *new)
int ft_lstsize (t_list *lst)
t_list * ft_lstlast (t_list *lst)
void ft_lstadd_back (t_list **lst, t_list *new)
int ft_printf (char const *str,...)
int ft_putchar (int pf)
int ft_putstr (char *str)
int ft_putnb (int pf)
int ft_puthexnum (unsigned int pf)
int ft_puthexnumax (unsigned int pf)
int ft_putunmath (unsigned int pf)
int ft_putpointer (void *pf)
int ft_selector (va_list pf, char const *str)
char * get_next_line (int fd)
char * ft_sstrchr (char *s, int j)
void * ft_caalloc (size_t nmbr, size_t sz)
char * ft_sstrjoin (char *fv, char *s)
int ft_sstrlen (char *ret)
long long ft_atol (const char *nptr)
void free_double_pointer (char **dbpt)
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 100
Definition at line 22 of file libft.h.
Typedef Documentation
t_list
typedef struct s_list t_list
Function Documentation
free_double_pointer()
void free_double_pointer (char ** dbpt)
Definition at line 15 of file ft_dbpt_free.c.
{
    int y;
    if (!dbpt)
        return ;
    y = 0;
    while (dbpt[y])
        y++;
    y--;
    while (y >= 0)
    {
        if (dbpt[y])
            free(dbpt[y]);
        y--;
    }
    free(dbpt);
}
Referenced by bin_execute(), env_execute(), and find_command().
ft_atoi()
int ft_atoi (const char * nptr)
Definition at line 13 of file ft_atoi.c.
{
    int nb;
    int i;
    int t;
    nb = 0;
    i = 0;
    t = 1;
    while ((nptr[i] >= 9 && nptr[i] <= 13) || nptr[i] == 32)
        i++;
    if (nptr[i] == '+' || nptr[i] == '-')
    {
        if (nptr[i] == '-')
            t = -t;
        i++;
    }
    while ((nptr[i] <= '9' && nptr[i] >= '0'))
    {
        nb = ((nb * 10) + nptr[i] - '0');
        i++;
    }
    return (t * nb);
}
ft_atol()
long long ft_atol (const char * nptr)
Definition at line 15 of file ft_atol.c.
{
    long long   nb;
    int         i;
    int         t;
    nb = 0;
    i = 0;
    t = 1;
    while ((nptr[i] >= 9 && nptr[i] <= 13) || nptr[i] == 32)
        i++;
    if (nptr[i] == '+' || nptr[i] == '-')
    {
        if (nptr[i] == '-')
            t = -t;
        i++;
    }
    while ((nptr[i] <= '9' && nptr[i] >= '0'))
    {
        nb = ((nb * 10) + nptr[i] - '0');
        i++;
    }
    return (t * nb);
}
ft_bzero()
void ft_bzero (void * s, size_t n)
Definition at line 15 of file ft_bzero.c.
{
    unsigned char   *dest;
    size_t          i;
    dest = s;
    i = 0;
    while (i < n)
    {
        dest[i] = 0;
        i++;
    }
}
ft_caalloc()
void * ft_caalloc (size_t nmbr, size_t sz)
Definition at line 71 of file get_next_line_utils.c.
{
    char    *p1;
    size_t  s;
    size_t  i;
    i = 0;
    s = nmemb * size;
    if (s >= 16711568 || s <= 0)
        return (NULL);
    p1 = malloc(s + 1);
    if (!p1)
        return (NULL);
    while (i <= s)
    {
        p1[i] = 0;
        i++;
    }
    return (p1);
}
Referenced by ft_readme(), ft_sstrjoin(), ft_ssubnstr(), and ft_ssubstr().
ft_calloc()
void * ft_calloc (size_t nmemb, size_t size)
Definition at line 15 of file ft_calloc.c.
{
    char    *p1;
    size_t  s;
    size_t  i;
    s = 0;
    i = 0;
    s = nmemb * size;
    if (s >= 16711568 || s <= 0)
        return (NULL);
    p1 = malloc(s + 1);
    if (!p1)
        return (NULL);
    while (i <= s)
    {
        p1[i] = 0;
        i++;
    }
    return (p1);
}
Referenced by ft_split(), ft_split2(), ft_substr(), init_command(), and init_environment_var().
ft_isalnum()
int ft_isalnum (int c)
Definition at line 13 of file ft_isalnum.c.
{
    if ((c >= '0' && c <= '9') || (c >= 65 && c <= 90) || (c >= 97 && c <= 122))
    {
        return (1);
    }
    return (0);
}
ft_isalpha()
int ft_isalpha (int c)
Definition at line 13 of file ft_isalpha.c.
{
    if ((c >= 65 && c <= 90) || (c >= 97 && c <= 122))
    {
        return (1);
    }
    return (0);
}
ft_isascii()
int ft_isascii (int c)
Definition at line 12 of file ft_isascii.c.
{
    if ((c >= 0 && c <= 127))
    {
        return (1);
    }
    return (0);
}
ft_isdigit()
int ft_isdigit (int c)
Definition at line 13 of file ft_isdigit.c.
{
    if (c == 0)
        return (0);
    if ((c >= '0' && c <= '9'))
    {
        return (1);
    }
    return (0);
}
ft_isprint()
int ft_isprint (int c)
Definition at line 13 of file ft_isprint.c.
{
    if ((c >= 32 && c <= 126))
    {
        return (1);
    }
    return (0);
}
ft_itoa()
char * ft_itoa (int n)
Definition at line 54 of file ft_itoa.c.
{
    char    *p3;
    int     ps;
    char    nb;
    nb = '+';
    if (n == 2147483647)
        return (ft_strdup("2147483647"));
    if (n == -2147483648)
        return (ft_strdup("-2147483648"));
    ps = ft_div(n);
    p3 = (char *)malloc(ft_isnegative(n) + ps + 1);
    if (!p3)
        return (NULL);
    if (n < 0)
    {
        n = -n;
        nb = '-';
    }
    ft_putnbr(n, ps, p3, nb);
    if (nb == '-')
        p3[0] = nb;
    return (p3);
}
References ft_div(), ft_isnegative(), ft_putnbr(), and ft_strdup().
ft_lstadd_back()
void ft_lstadd_back (t_list ** lst, t_list * new)
Definition at line 15 of file ft_lstadd_back_bonus.c.
{
    t_list  *nem;
    if (!lst || !new)
        return ;
    if (!*lst)
    {
        *lst = new;
        return ;
    }
    nem = *lst;
    while (nem->next != NULL)
        nem = nem->next;
    nem->next = new;
}
References s_list::next.
ft_lstadd_front()
void ft_lstadd_front (t_list ** lst, t_list * new)
Definition at line 15 of file ft_lstadd_front_bonus.c.
{
    new->next = *lst;
    *lst = new;
}
ft_lstlast()
t_list * ft_lstlast (t_list * lst)
Definition at line 15 of file ft_lstlast_bonus.c.
{
    if (!lst)
        return (NULL);
    while (lst->next != NULL)
        lst = lst->next;
    return (lst);
}
References s_list::next.
ft_lstnew()
t_list * ft_lstnew (void * content)
Definition at line 15 of file ft_lstnew_bonus.c.
{
    t_list  *newnod;
    newnod = (t_list *)malloc(sizeof(t_list));
    if (!newnod)
        return (NULL);
    newnod->content = content;
    newnod->next = NULL;
    return (newnod);
}
References s_list::content, and s_list::next.
ft_lstsize()
int ft_lstsize (t_list * lst)
Definition at line 15 of file ft_lstsize_bonus.c.
{
    int i;
    i = 1;
    if (!lst)
        return (0);
    while (lst->next != NULL)
    {
        lst = lst->next;
        i++;
    }
    return (i);
}
References s_list::next.
ft_memchr()
void * ft_memchr (const void * s, int c, size_t n)
Definition at line 14 of file ft_memchr.c.
{
    unsigned char   *str;
    size_t          i;
    str = (unsigned char *)s;
    i = 0;
    if (n == 0)
        return (NULL);
    while (i < n)
    {
        if (str[i] == (unsigned char)c)
            return (str + i);
        i++;
    }
    return (NULL);
}
ft_memcmp()
int ft_memcmp (const void * s1, const void * s2, size_t n)
Definition at line 15 of file ft_memcmp.c.
{
    unsigned char   *str1;
    unsigned char   *str2;
    size_t          l1;
    str1 = (unsigned char *)s1;
    str2 = (unsigned char *)s2;
    l1 = 0;
    if (n == 0)
        return (0);
    while (l1 < n)
    {
        if (*str1 != *str2)
            return (*str1 - *str2);
        l1++;
        str1++;
        str2++;
    }
    return (0);
}
ft_memcpy()
void * ft_memcpy (void * dest, const void * src, size_t n)
Definition at line 15 of file ft_memcpy.c.
{
    unsigned char   *desti;
    unsigned char   *srci;
    size_t          i;
    if (!dest && !src)
        return (NULL);
    desti = dest;
    srci = (unsigned char *)src;
    i = 0;
    while (i < n)
    {
        desti[i] = srci[i];
        i++;
    }
    return ((char *)desti);
}
ft_memmove()
void * ft_memmove (void * dest, const void * src, size_t n)
Definition at line 15 of file ft_memmove.c.
{
    unsigned char   *car;
    unsigned char   *whacala;
    int             w;
    whacala = (unsigned char *)dest;
    car = (unsigned char *)src;
    w = 0;
    if (!src && !dest)
        return (NULL);
    if (dest < src)
    {
        while ((size_t)w < n)
        {
            whacala[w] = car[w];
            w++;
        }
        return (whacala);
    }
    w = n;
    while (w != 0)
    {
        whacala[w - 1] = car[w - 1];
        w--;
    }
    return (whacala);
}
ft_memset()
void * ft_memset (void * s, int c, size_t n)
Definition at line 14 of file ft_memset.c.
{
    unsigned char   *dest;
    size_t          i;
    dest = (unsigned char *)s;
    i = 0;
    while (i < n)
    {
        dest[i] = c;
        i++;
    }
    return (dest);
}
ft_printf()
int ft_printf (char const * str, ...)
Definition at line 15 of file ft_printf.c.
{
    va_list pf;
    size_t  t;
    t = 0;
    va_start(pf, str);
    while (*str)
    {
        if (*str == '%')
        {
            str++;
            t += ft_selector(pf, str);
        }
        else
            t += ft_putchar(*str);
        str++;
    }
    va_end(pf);
    return (t);
}
References ft_putchar(), and ft_selector().
Referenced by echo_execute().
ft_putchar()
int ft_putchar (int pf)
Definition at line 15 of file ft_putchar.c.
{
    write(1, &pf, 1);
    return (1);
}
Referenced by ft_printf(), ft_puthexnum(), ft_puthexnumax(), ft_putstr(), ft_selector(), ft_trueputnb(), and ft_writenub().
ft_putchar_fd()
void ft_putchar_fd (char c, int fd)
Definition at line 15 of file ft_putchar_fd.c.
{
    write(fd, &c, 1);
}
Referenced by ft_putendl_fd(), ft_putnbr_fd(), and ft_putstr_fd().
ft_putendl_fd()
void ft_putendl_fd (char * s, int fd)
Definition at line 15 of file ft_putendl_fd.c.
{
    while (*s != '\0')
    {
        ft_putchar_fd(*s, fd);
        s++;
    }
    write(fd, "\n", 1);
}
References ft_putchar_fd().
ft_puthexnum()
int ft_puthexnum (unsigned int pf)
Definition at line 51 of file ft_puthexnum.c.
{
    int     i;
    char    *p3;
    if (pf == 0)
        return (ft_putchar('0'));
    i = ft_pos(pf);
    p3 = malloc(ft_pos(pf));
    if (!p3)
        return ('\0');
    ft_six(pf, p3, i - 1);
    free(p3);
    return (i - 1);
}
References ft_pos(), ft_putchar(), and ft_six().
Referenced by ft_selector().
ft_puthexnumax()
int ft_puthexnumax (unsigned int pf)
Definition at line 51 of file ft_puthexnumax.c.
{
    int     i;
    char    *p3;
    if (pf == 0)
        return (ft_putchar('0'));
    i = ft_pos(pf);
    p3 = malloc(ft_pos(pf) + 1);
    if (!p3)
    {
        free(p3);
        return ('\0');
    }
    ft_puthex(pf, p3, i);
    free(p3);
    return (i);
}
References ft_pos(), ft_putchar(), and ft_puthex().
Referenced by ft_selector().
ft_putnb()
int ft_putnb (int pf)
Definition at line 47 of file ft_putnb.c.
{
    ft_trueputnb(i);
    return (ft_count(i));
}
References ft_count(), and ft_trueputnb().
Referenced by ft_selector(), and ft_trueputnb().
ft_putnbr_fd()
void ft_putnbr_fd (int n, int fd)
Definition at line 15 of file ft_putnbr_fd.c.
{
    if (n == -2147483648)
        ft_putstr_fd("-2147483648", fd);
    else
    {
        if (n < 0)
        {
            n = -n;
            ft_putchar_fd('-', fd);
        }
        if (n > 9)
            ft_putnbr_fd(n / 10, fd);
        ft_putchar_fd(n % 10 + '0', fd);
    }
}
References ft_putchar_fd(), ft_putnbr_fd(), and ft_putstr_fd().
Referenced by ft_putnbr_fd().
ft_putpointer()
int ft_putpointer (void * pf)
Definition at line 51 of file ft_putpointer.c.
{
    unsigned long   p2;
    int             i;
    char            *p3;
    if (!pf)
        return (ft_putstr("(nil)"));
    p2 = (unsigned long)pf;
    i = ft_pos(p2);
    p3 = (char *)malloc(ft_pos(p2) + 3);
    if (!p3)
    {
        free(p3);
        return ('\0');
    }
    p3[0] = '0';
    p3[1] = 'x';
    ft_puthex(p2, p3, i + 2);
    free(p3);
    return (i + 2);
}
References ft_pos(), ft_puthex(), and ft_putstr().
Referenced by ft_selector().
ft_putstr()
int ft_putstr (char * str)
Definition at line 15 of file ft_putstr.c.
{
    int i;
    i = 0;
    if (!str)
        return (ft_putstr("(null)"));
    while (str[i])
    {
        i += ft_putchar(str[i]);
    }
    return (i);
}
References ft_putchar(), and ft_putstr().
Referenced by ft_puthex(), ft_puthex(), ft_putpointer(), ft_putstr(), ft_selector(), ft_six(), and ft_trueputnb().
ft_putstr_fd()
void ft_putstr_fd (char * s, int fd)
Definition at line 15 of file ft_putstr_fd.c.
{
    while (*s != '\0')
    {
        ft_putchar_fd(*s, fd);
        s++;
    }
}
References ft_putchar_fd().
Referenced by ft_putnbr_fd().
ft_putunmath()
int ft_putunmath (unsigned int pf)
Definition at line 35 of file ft_putunmath.c.
{
    ft_writenub(i);
    return (ft_count(i));
}
References ft_count(), and ft_writenub().
Referenced by ft_selector().
ft_selector()
int ft_selector (va_list pf, char const * str)
Definition at line 15 of file ft_selector.c.
{
    if (*str == 'c')
        return (ft_putchar(va_arg(pf, int)));
    if (*str == 's')
        return (ft_putstr(va_arg(pf, char *)));
    if (*str == 'X')
        return (ft_puthexnumax(va_arg(pf, unsigned long)));
    if (*str == 'x')
        return (ft_puthexnum(va_arg(pf, unsigned long)));
    if (*str == 'd' || *str == 'i')
        return (ft_putnb(va_arg(pf, int)));
    if (*str == 'p')
        return (ft_putpointer(va_arg(pf, void *)));
    if (*str == 'u')
        return (ft_putunmath(va_arg(pf, unsigned int)));
    if (*str == '%')
        return (ft_putchar('%'));
    return ('\0');
}
References ft_putchar(), ft_puthexnum(), ft_puthexnumax(), ft_putnb(), ft_putpointer(), ft_putstr(), and ft_putunmath().
Referenced by ft_printf().
ft_split()
char ** ft_split (char const * s, char c)
Definition at line 105 of file ft_split.c.
{
    char    **p3;
    size_t  p;
    p3 = NULL;
    p = 0;
    if (!s)
        return (NULL);
    p3 = (char **)ft_calloc((ft_worldette(s, c) + 1), sizeof(char *));
    if (!p3)
        return (NULL);
    return (ft_rapt(s, c, p3, p));
}
References ft_calloc(), ft_rapt(), and ft_worldette().
Referenced by env_deserialize(), and find_command().
ft_sstrchr()
char * ft_sstrchr (char * s, int j)
Definition at line 27 of file get_next_line_utils.c.
{
    int i;
    i = 0;
    if (s == NULL)
        return (NULL);
    while (s[i])
    {
        if (s[i] == (char)j)
            return (s + i);
        i++;
    }
    return (NULL);
}
Referenced by get_next_line().
ft_sstrjoin()
char * ft_sstrjoin (char * fv, char * s)
Definition at line 43 of file get_next_line_utils.c.
{
    int     i;
    int     j;
    char    *res;
    if (!s || !temp)
        return (NULL);
    res = NULL;
    j = 0;
    res = (char *)ft_caalloc(ft_sstrlen(s) + ft_sstrlen(temp), sizeof(char));
    if (!res)
        return (NULL);
    i = 0;
    while (temp[j])
    {
        res[j] = temp[j];
        j++;
    }
    while (s && s[i] && j < ft_sstrlen(s) + ft_sstrlen(temp))
    {
        res[j] = s[i];
        j++;
        i++;
    }
    return (free(s), free(temp), res);
}
References ft_caalloc(), and ft_sstrlen().
Referenced by ft_readme().
ft_sstrlen()
int ft_sstrlen (char * ret)
Definition at line 15 of file get_next_line_utils.c.
{
    int i;
    if (!ret)
        return (0);
    i = 0;
    while (ret[i])
        i++;
    return (i);
}
Referenced by ft_sstrjoin().
ft_strchr()
char * ft_strchr (const char * s, int c)
Definition at line 15 of file ft_strchr.c.
{
    if (!s)
        return (NULL);
    while (*s)
    {
        if (*s == (char)c)
            return ((char *)s);
        s++;
    }
    if (*s == (char)c)
        return ((char *)s);
    return (NULL);
}
Referenced by ft_ssubnstr(), and ft_strtrim().
ft_strdup()
char * ft_strdup (const char * s)
Definition at line 29 of file ft_strdup.c.
{
    char    *p1;
    p1 = malloc(ft_strlen(s) + 1);
    if (!p1)
        return (NULL);
    ft_strcpy((char *)s, p1);
    return (p1);
}
References ft_strcpy(), and ft_strlen().
Referenced by cd_execute(), env_get(), env_set(), ft_itoa(), serialize_arg(), and username().
ft_striteri()
void ft_striteri (char * s, void(*)(unsigned int, char *) f)
Definition at line 13 of file ft_striteri.c.
{
    unsigned int    i;
    i = 0;
    while (*s != '\0')
    {
        f(i, s);
        i++;
        s++;
    }
}
ft_strjoin()
char * ft_strjoin (char const * s1, char const * s2)
Definition at line 37 of file ft_strjoin.c.
{
    size_t  j;
    size_t  s;
    char    *p1;
    j = ft_strlen(s1);
    s = ft_strlen(s2);
    p1 = malloc(j + s + 1);
    if (!p1)
        return (NULL);
    return (ft_cpi(p1, s1, s2));
}
References ft_cpi(), and ft_strlen().
Referenced by cd_execute(), env_var_to_string(), get_final_path(), and username().
ft_strlcat()
size_t ft_strlcat (char * dst, const char * src, size_t size)
Definition at line 15 of file ft_strlcat.c.
{
    char    *jumpei;
    size_t  i;
    size_t  j;
    size_t  len1;
    i = 0;
    j = 0;
    jumpei = (char *)src;
    while (dst[i] && i < size)
        i++;
    len1 = i;
    if (len1 == size)
        return (ft_strlen(src) + size);
    while (jumpei[j] && i < (size - 1))
    {
        dst[i] = jumpei[j];
        i++;
        j++;
    }
    dst[i] = '\0';
    return (len1 + ft_strlen(src));
}
References ft_strlen().
ft_strlcpy()
size_t ft_strlcpy (char * dst, const char * src, size_t size)
Definition at line 15 of file ft_strlcpy.c.
{
    char    *p1;
    char    *p2;
    size_t  i;
    i = 0;
    p1 = (char *)src;
    p2 = (char *)dst;
    if (size == 0)
        return (ft_strlen(src));
    while (p1[i] && i < size - 1)
    {
        p2[i] = p1[i];
        i++;
    }
    p2[i] = '\0';
    return (ft_strlen(src));
}
References ft_strlen().
Referenced by init_redirect(), and parse_tokens_to_commands().
ft_strlen()
size_t ft_strlen (const char * str)
Definition at line 15 of file ft_strlen.c.
{
    size_t  i;
    if (!str)
        return (0);
    i = 0;
    while (str[i] != '\0')
    {
        i++;
    }
    return (i);
}
Referenced by echo_execute(), ft_ssubstr(), ft_strdup(), ft_strjoin(), ft_strlcat(), ft_strlcpy(), ft_strmapi(), ft_strtrim(), ft_substr(), get_command_function(), get_next_argument(), get_redirects_from_str_arr(), history_checker(), init_redirect(), main(), parse_tokens_to_commands(), special_char(), tokenize(), and var_name_filter().
ft_strmapi()
char * ft_strmapi (char const * s, char(*)(unsigned int, char) f)
Definition at line 14 of file ft_strmapi.c.
{
    unsigned int    i;
    char            *p3;
    if (!s || !f)
        return (NULL);
    p3 = (char *)malloc(ft_strlen(s) + 1);
    if (!p3)
        return (NULL);
    i = 0;
    while (s[i] != '\0')
    {
        p3[i] = f(i, s[i]);
        i++;
    }
    p3[i] = '\0';
    return (p3);
}
References ft_strlen().
ft_strncmp()
int ft_strncmp (const char * s1, const char * s2, size_t n)
Definition at line 15 of file ft_strncmp.c.
{
    unsigned int    i;
    unsigned char   *p3;
    unsigned char   *p2;
    if (!s1 || !s2 || n == 0)
        return (0);
    p3 = (unsigned char *)s1;
    p2 = (unsigned char *)s2;
    i = 0;
    if (!n)
        return (0);
    while ((size_t)i < n && (p3[i] || p2[i]))
    {
        if (p3[i] != p2[i])
            return (p3[i] - p2[i]);
        i++;
    }
    return (0);
}
Referenced by echo_execute(), find_command(), get_command_function(), get_next_argument(), get_redirection_type_from_str(), main(), special_char(), and var_name_filter().
ft_strnstr()
char * ft_strnstr (const char * big, const char * little, size_t len)
Definition at line 17 of file ft_strnstr.c.
{
    char    *found;
    size_t  n;
    size_t  i;
    if (*little == '\0')
        return ((char *)big);
    found = (char *)little;
    i = 0;
    while ((i < len) && big[i])
    {
        n = 0;
        while (big[i + n] == found[n] && i + n < len)
        {
            if (found[n] == '\0')
                return ((char *)&big[i]);
            n++;
        }
        if (found[n] == '\0')
            return ((char *)&big[i]);
        i++;
    }
    return (NULL);
}
ft_strrchr()
char * ft_strrchr (const char * s, int c)
Definition at line 15 of file ft_strrchr.c.
{
    char    *t;
    if (!s)
        return (NULL);
    t = NULL;
    while (*s)
    {
        if (*s == (char)c)
            t = (char *)s;
        s++;
    }
    if (*s == (char)c)
        t = ((char *)s);
    return (t);
}
ft_strtrim()
char * ft_strtrim (char const * s1, char const * set)
Definition at line 15 of file ft_strtrim.c.
{
    size_t  s;
    size_t  j;
    s = 0;
    j = ft_strlen(s1);
    if (!s1 && !set)
        return ((char *)malloc(1));
    while (ft_strchr(set, s1[s]) && s1[s] != '\0')
        s++;
    while (ft_strchr(set, s1[j]) && j > 0)
        j--;
    return (ft_substr(s1, s, (j - s + 1)));
}
References ft_strchr(), ft_strlen(), and ft_substr().
ft_substr()
char * ft_substr (char const * s, unsigned int start, size_t len)
Definition at line 15 of file ft_substr.c.
{
    char    *p2;
    size_t  i;
    i = 0;
    if (ft_strlen(s) <= start)
        return ((char *)ft_calloc(1, 1));
    if ((ft_strlen(s) - start) < len)
        p2 = malloc(ft_strlen(s) - start + 1);
    else
        p2 = malloc(len + 1);
    if (!p2)
        return (NULL);
    while (s[start] && i < len)
    {
        p2[i] = s[start];
        i++;
        start++;
    }
    p2[i] = '\0';
    return (p2);
}
References ft_calloc(), and ft_strlen().
Referenced by ft_strtrim(), and get_file_from_str().
ft_tolower()
int ft_tolower (int c)
Definition at line 13 of file ft_tolower.c.
{
    if ((c >= 65 && c <= 90))
    {
        c = c + 32;
    }
    return (c);
}
ft_toupper()
int ft_toupper (int c)
Definition at line 13 of file ft_toupper.c.
{
    if ((c >= 97 && c <= 122))
    {
        c = c - 32;
    }
    return (c);
}
get_next_line()
char * get_next_line (int fd)
Definition at line 103 of file get_next_line.c.
{
    static char *fv = NULL;
    char        *ret;
    ret = fv;
    if (fd < 0 || BUFFER_SIZE <= 0 || FOPEN_MAX < fd)
        return (NULL);
    fv = ft_readme(fd, fv);
    if (!fv)
        return (NULL);
    if (fv && ft_sstrchr(fv, '\n'))
    {
        ret = ft_ssubnstr(fv);
        fv = ft_extarct(fv);
        return (ret);
    }
    if (fv && fv == ret)
    {
        ret = ft_ssubstr(fv);
        free(fv);
        fv = NULL;
        return (ret);
    }
    return (get_next_line(fd));
}
References BUFFER_SIZE, ft_extarct(), ft_readme(), ft_sstrchr(), ft_ssubnstr(), ft_ssubstr(), and get_next_line().
Referenced by get_next_line().