Kyle's Doxygen Test: list/list.h File Reference
list.h File Reference
#include <stdbool.h>
#include <stdlib.h>
Classes
struct s_node
struct s_gen_list
struct s_iter
Typedefs
typedef struct s_node t_node
typedef struct s_gen_list t_gen_list
typedef struct s_iter t_iter
typedef char *(* t_element_to_string) (void *element)
Function that converts a list element into a string.
typedef void(* t_value_destroyer) (void *element)
Function that frees or destroys a value stored in the list.
typedef bool(* t_predicate) (void *element)
Predicate function used to test list elements.
typedef bool(* t_predicate_ctx) (void *element, void *context)
Predicate function with context.
typedef void(* t_apply_func) (void *element)
Function applied to each list element during traversal.
typedef void *(* t_string_to_element) (const char *str)
Function that converts a string into a list element.
Functions
t_gen_list * init_list (void)
Initialize an empty list.
void destroy_gen_list (t_gen_list *list, t_value_destroyer value_destroyer)
Destroy the entire list and its nodes.
void push_end (t_gen_list *list, void *value)
Insert a value at the end of the list (O(1)).
void push_front (t_gen_list *list, void *value)
Insert a value at the beginning of the list (O(1)).
void * pop_front (t_gen_list *list)
Remove the first node of the list and return its value.
void remove_if (t_gen_list *list, t_predicate predicate, t_value_destroyer value_destroyer)
Remove nodes from the list that satisfy a condition.
void remove_if_ctx (t_gen_list *list, t_predicate_ctx predicate, void *context, t_value_destroyer value_destroyer)
Remove nodes from the list that satisfy a condition with context.
void traverse (t_gen_list *list, t_apply_func func)
Traverse all elements of the list and apply a function to each value.
void * find_in_list (t_gen_list *list, t_predicate predicate)
Find the first element that satisfies a predicate.
void * find_in_list_ctx (t_gen_list *list, t_predicate_ctx predicate, void *context)
Find the first element in the list that satisfies a predicate with context.
bool contains_in_list (t_gen_list *list, t_predicate predicate)
Check if the list contains an element that satisfies a predicate.
bool contains_in_list_ctx (t_gen_list *list, t_predicate_ctx predicate, void *context)
Check if the list contains an element that satisfies a predicate with context.
t_iter iter_start (t_gen_list *list)
Initialize an iterator at the start of the list.
void * iter_next (t_iter *it)
Get the next value from the list using the iterator and advance it.
char * serialize_to_string (t_gen_list *list, t_element_to_string element_to_string)
Convert a generic list into a single string representation.
char ** serialize_to_string_array (t_gen_list *list, t_element_to_string element_to_string)
Convert a generic list into an array of strings.
t_gen_list * deserialize_from_string_array (char **array, t_string_to_element string_to_element)
Typedef Documentation
t_apply_func
typedef void(* t_apply_func) (void *element)
Function applied to each list element during traversal.
Parameters
element Pointer to the element to process.
Definition at line 83 of file list.h.
t_element_to_string
typedef char *(* t_element_to_string) (void *element)
Function that converts a list element into a string.
Parameters
element Pointer to the element to convert.
Returns
A dynamically allocated string representation of the element.
Definition at line 52 of file list.h.
t_gen_list
typedef struct s_gen_list t_gen_list
t_iter
typedef struct s_iter t_iter
t_node
typedef struct s_node t_node
t_predicate
typedef bool(* t_predicate) (void *element)
Predicate function used to test list elements.
Parameters
element Pointer to the element to test.
Returns
true if the element satisfies the condition, false otherwise.
Definition at line 67 of file list.h.
t_predicate_ctx
typedef bool(* t_predicate_ctx) (void *element, void *context)
Predicate function with context.
Parameters
element Pointer to the element to test.
context Pointer to extra data required by the predicate.
Returns
true if the element satisfies the condition, false otherwise.
Definition at line 76 of file list.h.
t_string_to_element
typedef void *(* t_string_to_element) (const char *str)
Function that converts a string into a list element.
Parameters
str Null-terminated string to convert.
Returns
A dynamically allocated element, or NULL on failure.
Definition at line 91 of file list.h.
t_value_destroyer
typedef void(* t_value_destroyer) (void *element)
Function that frees or destroys a value stored in the list.
Parameters
element Pointer to the element to destroy.
Definition at line 59 of file list.h.
Function Documentation
contains_in_list()
bool contains_in_list (t_gen_list * list, t_predicate predicate)
Check if the list contains an element that satisfies a predicate.
Parameters
list List to search.
predicate Predicate function to test elements.
Returns
true if a matching element is found, false otherwise.
contains_in_list_ctx()
bool contains_in_list_ctx (t_gen_list * list, t_predicate_ctx predicate, void * context)
Check if the list contains an element that satisfies a predicate with context.
Parameters
list List to search.
predicate Predicate function that takes (element, context).
context Context pointer passed to the predicate.
Returns
true if a matching element is found, false otherwise.
Definition at line 247 of file list.c.
{
    return (find_in_list_ctx(list, predicate, context) != NULL);
}
References find_in_list_ctx().
Referenced by env_has().
deserialize_from_string_array()
t_gen_list * deserialize_from_string_array (char ** array, t_string_to_element string_to_element)
Convert a null-terminated array of strings into a generic linked list.
Parameters
array Null-terminated array of strings.
string_to_element Function to convert each string into a list element.
Returns
Pointer to a newly allocated list, or NULL on error.
Definition at line 389 of file list.c.
{
    if (!array || !string_to_element)
        return NULL;
    t_gen_list *list = (t_gen_list *)malloc(sizeof(t_gen_list));
    if (!list) return NULL;
    list->head = NULL;
    list->size = 0;
    t_node *last = NULL;
    for (size_t i = 0; array[i] != NULL; i++) {
        void *value = string_to_element(array[i]);
        if (!value) goto error_cleanup;
        t_node *node = (t_node *)malloc(sizeof(t_node));
        if (!node) {
            free(value);
            goto error_cleanup;
        }
        node->value = value;
        node->next = NULL;
        if (!list->head)
            list->head = node;
        else
            last->next = node;
        last = node;
        list->size++;
    }
    return list;
error_cleanup:
    t_node *tmp = list->head;
    while (tmp) {
        t_node *next = tmp->next;
        free(tmp->value);
        free(tmp);
        tmp = next;
    }
    free(list);
    return NULL;
}
References s_gen_list::head, s_node::next, s_gen_list::size, and s_node::value.
destroy_gen_list()
void destroy_gen_list (t_gen_list * list, t_value_destroyer value_destroyer)
Destroy the entire list and its nodes.
Parameters
list List to destroy.
value_destroyer Function to free each stored value, can be NULL.
find_in_list()
void * find_in_list (t_gen_list * list, t_predicate predicate)
Find the first element that satisfies a predicate.
Parameters
list List to search.
predicate Predicate function to test each element.
Returns
Value of the first node that satisfies the condition, or NULL if none found.
find_in_list_ctx()
void * find_in_list_ctx (t_gen_list * list, t_predicate_ctx predicate, void * context)
Find the first element in the list that satisfies a predicate with context.
Parameters
list List to search.
predicate Predicate function that takes (element, context).
context Context pointer passed to the predicate.
Returns
Value of the first matching node, or NULL if none found.
Definition at line 233 of file list.c.
{
    t_node *curr = list->head;
    while (curr)
    {
        if (predicate(curr->value, context))
            return curr->value;
        curr = curr->next;
    }
    return NULL;
}
References s_gen_list::head, s_node::next, and s_node::value.
Referenced by contains_in_list_ctx(), env_get(), and env_set().
init_list()
t_gen_list * init_list (void)
Initialize an empty list.
Returns
Pointer to the created list, or NULL if allocation fails.
Definition at line 17 of file list.c.
{
    t_gen_list  *list;
    list = malloc(sizeof(t_gen_list));
    if (!list)
        return (NULL);
    list->head = NULL;
    list->tail = NULL;
    list->size = 0;
    return (list);
}
References s_gen_list::head, s_gen_list::size, and s_gen_list::tail.
Referenced by env_deserialize(), get_redirects_from_str_arr(), parse_tokens_to_commands(), and tokenize().
iter_next()
void * iter_next (t_iter * it)
Get the next value from the list using the iterator and advance it.
Parameters
it Iterator of the list.
Returns
Value of the current node and advances, or NULL if the end is reached.
Definition at line 217 of file list.c.
{
    void    *val;
    if (!it || !it->current)
        return (NULL);
    val = it->current->value;
    it->current = it->current->next;
    return (val);
}
References s_iter::current, s_node::next, and s_node::value.
Referenced by cd_execute(), execute_commands_with_pipes(), parse_tokens_to_commands(), print_command(), print_commands(), and print_tokens().
iter_start()
t_iter iter_start (t_gen_list * list)
Initialize an iterator at the start of the list.
Parameters
list List to iterate.
Returns
Iterator pointing to the first node.
Definition at line 209 of file list.c.
{
    t_iter  it;
    it.current = list ? list->head : NULL;
    return (it);
}
References s_iter::current, and s_gen_list::head.
Referenced by cd_execute(), execute_commands_with_pipes(), parse_tokens_to_commands(), print_command(), print_commands(), and print_tokens().
pop_front()
void * pop_front (t_gen_list * list)
Remove the first node of the list and return its value.
Parameters
list List from which to remove the first node.
Returns
Value stored in the first node, or NULL if the list is empty.
Definition at line 71 of file list.c.
{
    t_node  *node;
    void    *val;
    if (!list || !list->head)
        return (NULL);
    node = list->head;
    val = node->value;
    list->head = node->next;
    if (!list->head)
        list->tail = NULL;
    free(node);
    list->size--;
    return (val);
}
References s_gen_list::head, s_node::next, s_gen_list::size, s_gen_list::tail, and s_node::value.
push_end()
void push_end (t_gen_list * list, void * value)
Insert a value at the end of the list (O(1)).
Parameters
list List where the value will be inserted.
value Pointer to the value to insert.
Definition at line 30 of file list.c.
{
    t_node  *node;
    if (!list)
        return ;
    node = malloc(sizeof(t_node));
    if (!node)
        return ;
    node->value = value;
    node->next = NULL;
    if (!list->head)
    {
        list->head = node;
        list->tail = node;
    }
    else
    {
        list->tail->next = node;
        list->tail = node;
    }
    list->size++;
}
References s_gen_list::head, s_node::next, s_gen_list::size, s_gen_list::tail, and s_node::value.
Referenced by env_deserialize(), get_redirects_from_str_arr(), parse_tokens_to_commands(), and tokenize().
push_front()
void push_front (t_gen_list * list, void * value)
Insert a value at the beginning of the list (O(1)).
Parameters
list List where the value will be inserted.
value Pointer to the value to insert.
Definition at line 54 of file list.c.
{
    t_node  *node;
    if (!list)
        return ;
    node = malloc(sizeof(t_node));
    if (!node)
        return ;
    node->value = value;
    node->next = list->head;
    list->head = node;
    if (!list->tail)
        list->tail = node;
    list->size++;
}
References s_gen_list::head, s_node::next, s_gen_list::size, s_gen_list::tail, and s_node::value.
Referenced by env_set().
remove_if()
void remove_if (t_gen_list * list, t_predicate predicate, t_value_destroyer value_destroyer)
Remove nodes from the list that satisfy a condition.
Parameters
list List to modify.
predicate Predicate function to decide which nodes to remove.
value_destroyer Function to free the value of each removed node.
remove_if_ctx()
void remove_if_ctx (t_gen_list * list, t_predicate_ctx predicate, void * context, t_value_destroyer value_destroyer)
Remove nodes from the list that satisfy a condition with context.
Parameters
list List to modify.
predicate Predicate function that takes (element, context).
context Extra pointer passed to the predicate on each call.
value_destroyer Function to free the value of each removed node, can be NULL.
serialize_to_string()
char * serialize_to_string (t_gen_list * list, t_element_to_string element_to_string)
Convert a generic list into a single string representation.
Parameters
list Pointer to the list to serialize.
element_to_string Function that converts each element to a string.
Returns
Dynamically allocated string representing the list.
Convert a list into a single string in format: [elem1, elem2, ...]
Definition at line 284 of file list.c.
{
    if (!list || !element_to_string)
        return NULL;
    // First, calculate total length needed
    size_t total_len = 2; // '[' + ']'
    t_node *current = list->head;
    size_t count = 0;
    while (current)
    {
        char *elem_str = element_to_string(current->value);
        if (!elem_str)
            return NULL;
        total_len += str_len(elem_str);
        if (current->next)
            total_len += 2; // for ", "
        free(elem_str);
        current = current->next;
        count++;
    }
    char *result = malloc(total_len + 1); // +1 for '\0'
    if (!result)
        return NULL;
    size_t pos = 0;
    result[pos++] = '[';
    result[pos] = '\0';
    current = list->head;
    size_t i = 0;
    while (current)
    {
        char *elem_str = element_to_string(current->value);
        if (!elem_str)
        {
            free(result);
            return NULL;
        }
        str_copy_at(result, elem_str, &pos);
        free(elem_str);
        if (current->next)
        {
            result[pos++] = ',';
            result[pos++] = ' ';
            result[pos] = '\0';
        }
        current = current->next;
        i++;
    }
    result[pos++] = ']';
    result[pos] = '\0';
    return result;
}
References s_gen_list::head, s_node::next, str_copy_at(), str_len(), and s_node::value.
serialize_to_string_array()
char ** serialize_to_string_array (t_gen_list * list, t_element_to_string element_to_string)
Convert a generic list into an array of strings.
Parameters
list Pointer to the list to serialize.
element_to_string Function that converts each element to a string.
Returns
Dynamically allocated null-terminated array of strings, one per element.
Convert a list into an array of strings. Each element is a string returned by element_to_string. The array is null-terminated.
Definition at line 352 of file list.c.
{
    if (!list || !element_to_string)
        return NULL;
    char **array = malloc((list->size + 1) * sizeof(char *));
    if (!array)
        return NULL;
    t_node *current = list->head;
    size_t i = 0;
    while (current)
    {
        array[i] = element_to_string(current->value);
        if (!array[i])
        {
            for (size_t j = 0; j < i; j++)
                free(array[j]);
            free(array);
            return NULL;
        }
        i++;
        current = current->next;
    }
    array[i] = NULL; // Null-terminate
    return array;
}
References s_gen_list::head, s_node::next, s_gen_list::size, and s_node::value.
Referenced by bin_execute(), and env_serialize().
traverse()
void traverse (t_gen_list * list, t_apply_func func)
Traverse all elements of the list and apply a function to each value.
Parameters
list List to traverse.
func Function to apply to each value.