Kyle's Doxygen Test: list/list.c File Reference
list.c File Reference
#include "list.h"
#include "../libft/libft.h"
#include <stdlib.h>
Functions
t_gen_list * init_list (void)
Initialize an empty list.
void push_end (t_gen_list *list, void *value)
Insert a value at the end of the list (O(1)).
void push_front (t_gen_list *list, void *value)
Insert a value at the beginning of the list (O(1)).
void * pop_front (t_gen_list *list)
Remove the first node of the list and return its value.
void destroy_gen_list (t_gen_list *list, void(value_destroyer)(void *))
void traverse (t_gen_list *list, void(*func)(void *))
void remove_if (t_gen_list *list, bool(*predicate)(void *), void(*value_destroyer)(void *))
void remove_if_ctx (t_gen_list *list, bool(*predicate)(void *element, void *context), void *context, void(*value_destroyer)(void *))
void * find_in_list (t_gen_list *list, bool(*predicate)(void *))
t_iter iter_start (t_gen_list *list)
Initialize an iterator at the start of the list.
void * iter_next (t_iter *it)
Get the next value from the list using the iterator and advance it.
bool contains_in_list (t_gen_list *list, bool(*predicate)(void *))
void * find_in_list_ctx (t_gen_list *list, bool(*predicate)(void *element, void *context), void *context)
Find the first element in the list that satisfies a predicate with context.
bool contains_in_list_ctx (t_gen_list *list, bool(*predicate)(void *element, void *context), void *context)
Check if the list contains an element that satisfies a predicate with context.
static size_t str_len (const char *s)
static void str_copy_at (char *dest, const char *src, size_t *pos)
char * serialize_to_string (t_gen_list *list, t_element_to_string element_to_string)
Convert a generic list into a single string representation.
char ** serialize_to_string_array (t_gen_list *list, t_element_to_string element_to_string)
Convert a generic list into an array of strings.
t_gen_list * deserialize_from_string_array (char **array, t_string_to_element string_to_element)
Function Documentation
contains_in_list()
bool contains_in_list (t_gen_list * list, bool(*)(void *) predicate)
Definition at line 228 of file list.c.
{
    return (find_in_list(list, predicate) != NULL);
}
References find_in_list().
contains_in_list_ctx()
bool contains_in_list_ctx (t_gen_list * list, t_predicate_ctx predicate, void * context)
Check if the list contains an element that satisfies a predicate with context.
Parameters
list List to search.
predicate Predicate function that takes (element, context).
context Context pointer passed to the predicate.
Returns
true if a matching element is found, false otherwise.
Definition at line 247 of file list.c.
{
    return (find_in_list_ctx(list, predicate, context) != NULL);
}
References find_in_list_ctx().
Referenced by env_has().
deserialize_from_string_array()
t_gen_list * deserialize_from_string_array (char ** array, t_string_to_element string_to_element)
Convert a null-terminated array of strings into a generic linked list.
Parameters
array Null-terminated array of strings.
string_to_element Function to convert each string into a list element.
Returns
Pointer to a newly allocated list, or NULL on error.
Definition at line 389 of file list.c.
{
    if (!array || !string_to_element)
        return NULL;
    t_gen_list *list = (t_gen_list *)malloc(sizeof(t_gen_list));
    if (!list) return NULL;
    list->head = NULL;
    list->size = 0;
    t_node *last = NULL;
    for (size_t i = 0; array[i] != NULL; i++) {
        void *value = string_to_element(array[i]);
        if (!value) goto error_cleanup;
        t_node *node = (t_node *)malloc(sizeof(t_node));
        if (!node) {
            free(value);
            goto error_cleanup;
        }
        node->value = value;
        node->next = NULL;
        if (!list->head)
            list->head = node;
        else
            last->next = node;
        last = node;
        list->size++;
    }
    return list;
error_cleanup:
    t_node *tmp = list->head;
    while (tmp) {
        t_node *next = tmp->next;
        free(tmp->value);
        free(tmp);
        tmp = next;
    }
    free(list);
    return NULL;
}
References s_gen_list::head, s_node::next, s_gen_list::size, and s_node::value.
destroy_gen_list()
void destroy_gen_list (t_gen_list * list, void(value_destroyer)(void *))
Definition at line 88 of file list.c.
{
    t_node  *current;
    t_node  *tmp;
    if (!list)
        return ;
    current = list->head;
    while (current)
    {
        tmp = current->next;
        if (value_destroyer)
            value_destroyer(current->value);
        free(current);
        current = tmp;
    }
    free(list);
}
References s_gen_list::head, s_node::next, and s_node::value.
Referenced by destroy_command(), env_destroy(), main(), parse_tokens_to_commands(), and tokenize().
find_in_list()
void * find_in_list (t_gen_list * list, bool(*)(void *) predicate)
Definition at line 193 of file list.c.
{
    t_node  *current;
    if (!list || !predicate)
        return (NULL);
    current = list->head;
    while (current)
    {
        if (predicate(current->value))
            return (current->value);
        current = current->next;
    }
    return (NULL);
}
References s_gen_list::head, s_node::next, and s_node::value.
Referenced by contains_in_list().
find_in_list_ctx()
void * find_in_list_ctx (t_gen_list * list, t_predicate_ctx predicate, void * context)
Find the first element in the list that satisfies a predicate with context.
Parameters
list List to search.
predicate Predicate function that takes (element, context).
context Context pointer passed to the predicate.
Returns
Value of the first matching node, or NULL if none found.
Definition at line 233 of file list.c.
{
    t_node *curr = list->head;
    while (curr)
    {
        if (predicate(curr->value, context))
            return curr->value;
        curr = curr->next;
    }
    return NULL;
}
References s_gen_list::head, s_node::next, and s_node::value.
Referenced by contains_in_list_ctx(), env_get(), and env_set().
init_list()
t_gen_list * init_list (void)
Initialize an empty list.
Returns
Pointer to the created list, or NULL if allocation fails.
Definition at line 17 of file list.c.
{
    t_gen_list  *list;
    list = malloc(sizeof(t_gen_list));
    if (!list)
        return (NULL);
    list->head = NULL;
    list->tail = NULL;
    list->size = 0;
    return (list);
}
References s_gen_list::head, s_gen_list::size, and s_gen_list::tail.
Referenced by env_deserialize(), get_redirects_from_str_arr(), parse_tokens_to_commands(), and tokenize().
iter_next()
void * iter_next (t_iter * it)
Get the next value from the list using the iterator and advance it.
Parameters
it Iterator of the list.
Returns
Value of the current node and advances, or NULL if the end is reached.
Definition at line 217 of file list.c.
{
    void    *val;
    if (!it || !it->current)
        return (NULL);
    val = it->current->value;
    it->current = it->current->next;
    return (val);
}
References s_iter::current, s_node::next, and s_node::value.
Referenced by cd_execute(), execute_commands_with_pipes(), parse_tokens_to_commands(), print_command(), print_commands(), and print_tokens().
iter_start()
t_iter iter_start (t_gen_list * list)
Initialize an iterator at the start of the list.
Parameters
list List to iterate.
Returns
Iterator pointing to the first node.
Definition at line 209 of file list.c.
{
    t_iter  it;
    it.current = list ? list->head : NULL;
    return (it);
}
References s_iter::current, and s_gen_list::head.
Referenced by cd_execute(), execute_commands_with_pipes(), parse_tokens_to_commands(), print_command(), print_commands(), and print_tokens().
pop_front()
void * pop_front (t_gen_list * list)
Remove the first node of the list and return its value.
Parameters
list List from which to remove the first node.
Returns
Value stored in the first node, or NULL if the list is empty.
Definition at line 71 of file list.c.
{
    t_node  *node;
    void    *val;
    if (!list || !list->head)
        return (NULL);
    node = list->head;
    val = node->value;
    list->head = node->next;
    if (!list->head)
        list->tail = NULL;
    free(node);
    list->size--;
    return (val);
}
References s_gen_list::head, s_node::next, s_gen_list::size, s_gen_list::tail, and s_node::value.
push_end()
void push_end (t_gen_list * list, void * value)
Insert a value at the end of the list (O(1)).
Parameters
list List where the value will be inserted.
value Pointer to the value to insert.
Definition at line 30 of file list.c.
{
    t_node  *node;
    if (!list)
        return ;
    node = malloc(sizeof(t_node));
    if (!node)
        return ;
    node->value = value;
    node->next = NULL;
    if (!list->head)
    {
        list->head = node;
        list->tail = node;
    }
    else
    {
        list->tail->next = node;
        list->tail = node;
    }
    list->size++;
}
References s_gen_list::head, s_node::next, s_gen_list::size, s_gen_list::tail, and s_node::value.
Referenced by env_deserialize(), get_redirects_from_str_arr(), parse_tokens_to_commands(), and tokenize().
push_front()
void push_front (t_gen_list * list, void * value)
Insert a value at the beginning of the list (O(1)).
Parameters
list List where the value will be inserted.
value Pointer to the value to insert.
Definition at line 54 of file list.c.
{
    t_node  *node;
    if (!list)
        return ;
    node = malloc(sizeof(t_node));
    if (!node)
        return ;
    node->value = value;
    node->next = list->head;
    list->head = node;
    if (!list->tail)
        list->tail = node;
    list->size++;
}
References s_gen_list::head, s_node::next, s_gen_list::size, s_gen_list::tail, and s_node::value.
Referenced by env_set().
remove_if()
void remove_if (t_gen_list * list, bool(*)(void *) predicate, void(*)(void *) value_destroyer)
Definition at line 121 of file list.c.
{
    t_node  *current;
    t_node  *prev;
    t_node  *next;
    if (!list || !predicate)
        return ;
    current = list->head;
    prev = NULL;
    while (current)
    {
        next = current->next;
        if (predicate(current->value))
        {
            if (prev)
                prev->next = next;
            else
                list->head = next;
            if (current == list->tail)
                list->tail = prev;
            if (value_destroyer)
                value_destroyer(current->value);
            free(current);
            list->size--;
        }
        else
        {
            prev = current;
        }
        current = next;
    }
}
References s_gen_list::head, s_node::next, s_gen_list::size, s_gen_list::tail, and s_node::value.
remove_if_ctx()
void remove_if_ctx (t_gen_list * list, bool(*)(void *element, void *context) predicate, void * context, void(*)(void *) value_destroyer)
Definition at line 156 of file list.c.
{
    t_node  *current;
    t_node  *prev;
    t_node  *next;
    if (!list || !predicate)
        return ;
    current = list->head;
    prev = NULL;
    while (current)
    {
        next = current->next;
        if (predicate(current->value, context))
        {
            if (prev)
                prev->next = next;
            else
                list->head = next;
            if (current == list->tail)
                list->tail = prev;
            if (value_destroyer)
                value_destroyer(current->value);
            free(current);
            list->size--;
        }
        else
        {
            prev = current;
        }
        current = next;
    }
}
References s_gen_list::head, s_node::next, s_gen_list::size, s_gen_list::tail, and s_node::value.
Referenced by env_unset().
serialize_to_string()
char * serialize_to_string (t_gen_list * list, t_element_to_string element_to_string)
Convert a generic list into a single string representation.
Convert a list into a single string in format: [elem1, elem2, ...]
Definition at line 284 of file list.c.
{
    if (!list || !element_to_string)
        return NULL;
    // First, calculate total length needed
    size_t total_len = 2; // '[' + ']'
    t_node *current = list->head;
    size_t count = 0;
    while (current)
    {
        char *elem_str = element_to_string(current->value);
        if (!elem_str)
            return NULL;
        total_len += str_len(elem_str);
        if (current->next)
            total_len += 2; // for ", "
        free(elem_str);
        current = current->next;
        count++;
    }
    char *result = malloc(total_len + 1); // +1 for '\0'
    if (!result)
        return NULL;
    size_t pos = 0;
    result[pos++] = '[';
    result[pos] = '\0';
    current = list->head;
    size_t i = 0;
    while (current)
    {
        char *elem_str = element_to_string(current->value);
        if (!elem_str)
        {
            free(result);
            return NULL;
        }
        str_copy_at(result, elem_str, &pos);
        free(elem_str);
        if (current->next)
        {
            result[pos++] = ',';
            result[pos++] = ' ';
            result[pos] = '\0';
        }
        current = current->next;
        i++;
    }
    result[pos++] = ']';
    result[pos] = '\0';
    return result;
}
References s_gen_list::head, s_node::next, str_copy_at(), str_len(), and s_node::value.
serialize_to_string_array()
char ** serialize_to_string_array (t_gen_list * list, t_element_to_string element_to_string)
Convert a generic list into an array of strings.
Convert a list into an array of strings. Each element is a string returned by element_to_string. The array is null-terminated.
Definition at line 352 of file list.c.
{
    if (!list || !element_to_string)
        return NULL;
    char **array = malloc((list->size + 1) * sizeof(char *));
    if (!array)
        return NULL;
    t_node *current = list->head;
    size_t i = 0;
    while (current)
    {
        array[i] = element_to_string(current->value);
        if (!array[i])
        {
            for (size_t j = 0; j < i; j++)
                free(array[j]);
            free(array);
            return NULL;
        }
        i++;
        current = current->next;
    }
    array[i] = NULL; // Null-terminate
    return array;
}
References s_gen_list::head, s_node::next, s_gen_list::size, and s_node::value.
Referenced by bin_execute(), and env_serialize().
str_copy_at()
static void str_copy_at (char * dest, const char * src, size_t * pos) static
Definition at line 264 of file list.c.
{
    size_t i = 0;
    while (src[i] != '\0')
    {
        dest[*pos] = src[i];
        (*pos)++;
        i++;
    }
    dest[*pos] = '\0';
}
Referenced by serialize_to_string().
str_len()
static size_t str_len (const char * s) static
Definition at line 255 of file list.c.
{
    size_t len = 0;
    while (s[len] != '\0')
        len++;
    return len;
}
Referenced by serialize_to_string().
traverse()
void traverse (t_gen_list * list, void(*)(void *) func)
Definition at line 107 of file list.c.
{
    t_node  *current;
    if (!list || !func)
        return ;
    current = list->head;
    while (current)
    {
        func(current->value);
        current = current->next;
    }
}
References s_gen_list::head, s_node::next, and s_node::value.