Kyle's Doxygen Test: src/minishell.c File Reference
minishell.c File Reference
#include "../include/bin_commandss_execution.h"
#include "../include/command.h"
#include "../include/environment.h"
#include "../list/list.h"
#include "../include/parser.h"
#include "../include/redirect_asignation.h"
#include "../include/tokenizer.h"
#include "../libft/libft.h"
#include "readline/history.h"
#include "readline/readline.h"
#include <signal.h>
#include <stdbool.h>
#include <unistd.h>
Functions
static char * history_checker (char *cmd)
char * check_cmd (char *cmd)
char * username (t_gen_list *env)
void sigint_handler (int sig)
void signals_init (void)
void print_tokens (t_gen_list *tokens)
void print_redirect (t_redirect *redir)
void print_command (t_command *cmd, int index)
void print_commands (t_gen_list *commands)
void destroy_token_data (void *token_ptr)
int main (int args, char **environment_var_str_array)
Variables
volatile sig_atomic_t g_signal = 0
Function Documentation
check_cmd()
char * check_cmd (char * cmd)
Definition at line 50 of file minishell.c.
{
    int i;
    int b;
    b = 0;
    i = 0;
    if (history_checker(cmd) == NULL)
        return (NULL);
    while (cmd[i])
    {
        if (cmd[i] == '"')
            b = 1;
        i++;
        while (cmd[i] && b == 1)
        {
            if (cmd[i] == '"')
                b = 0;
            i++;
        }
    }
    if (b != 0)
    {
        add_history(cmd);
        return (NULL);
    }
    return (cmd);
}
References history_checker().
Referenced by main().
destroy_token_data()
void destroy_token_data (void * token_ptr)
Definition at line 218 of file minishell.c.
{
    destroy_token((t_token *) token_ptr);
}
References destroy_token().
Referenced by main().
history_checker()
static char * history_checker (char * cmd) static
Definition at line 29 of file minishell.c.
{
    int i;
    i = 0;
    if (cmd[0] == '|' || cmd[ft_strlen(cmd)] == '|')
    {
        add_history(cmd);
        return (NULL);
    }
    while (cmd[i])
    {
        if (ft_ispace(cmd[i]) == 0)
            break ;
        i++;
    }
    if (cmd[i] == '\0')
        return (NULL);
    return (cmd);
}
References ft_ispace(), and ft_strlen().
Referenced by check_cmd().
main()
int main (int args, char ** environment_var_str_array)
Definition at line 223 of file minishell.c.
{
    t_gen_list  *tokens;
    t_gen_list  *current_commands;
    t_gen_list  *envioroment_vars;
    bool        finish;
    char        *line;
    char        *name;
    if (args > 1)
        exit(0);
    signals_init();
    envioroment_vars = env_deserialize(environment_var_str_array
            + 2);
    name = username(envioroment_vars);
    finish = false;
    while (!finish)
    {
        line = readline(name);
        if ((ft_strlen(line) != 0 && ft_strncmp(line, "exit",
                    ft_strlen(line)) == 0) || line == NULL)
            finish = true;
        else if (ft_strlen(line) != 0)
        {
            if (check_cmd(line) == NULL)
                continue ;
            add_history(line);
            tokens = tokenize(line);
            //print_tokens(tokens);
            if (!tokens)
            {
                perror("Tokenization error ");
                continue ;
            }
            current_commands = parse_tokens_to_commands(tokens);
            destroy_gen_list(tokens, destroy_token_data);
            if (!current_commands)
            {
                perror("Parsing error ");
                continue ;
            }
            //print_commands(current_commands);
            execute_commands_with_pipes(current_commands, envioroment_vars);
        }
        free(line);
        line = NULL;
        destroy_gen_list(current_commands, destroy_command);
        current_commands = NULL;
    }
    env_destroy(envioroment_vars);
    free(name);
}
References check_cmd(), destroy_command(), destroy_gen_list(), destroy_token_data(), env_deserialize(), env_destroy(), execute_commands_with_pipes(), ft_strlen(), ft_strncmp(), parse_tokens_to_commands(), signals_init(), tokenize(), and username().
print_command()
void print_command (t_command * cmd, int index)
Definition at line 171 of file minishell.c.
{
    if (!cmd) return;
    printf("Command #%d:\n", index);
    //Imprimir args
    if (cmd->args && cmd->args->size > 0) {
        printf("  Args:\n");
        t_iter arg_it = iter_start(cmd->args);
        char *arg;
        while ((arg = (char *)iter_next(&arg_it)) != NULL) {
            printf("    %s\n", arg);
        }
    } else {
        printf("  Args: (none)\n");
    }
    //Imprimir redirects
    if (cmd->redirects && cmd->redirects->size > 0) {
        printf("  Redirects:\n");
        t_iter red_it = iter_start(cmd->redirects);
        t_redirect *redir;
        while ((redir = (t_redirect *)iter_next(&red_it)) != NULL) {
            print_redirect(redir);
        }
    } else {
        printf("  Redirects: (none)\n");
    }
    printf("\n");
}
References s_command::args, iter_next(), iter_start(), print_redirect(), s_command::redirects, and s_gen_list::size.
Referenced by print_commands().
print_commands()
void print_commands (t_gen_list * commands)
Definition at line 204 of file minishell.c.
{
    if (!commands || commands->size == 0) {
        printf("No commands to print.\n");
        return;
    }
    t_iter it = iter_start(commands);
    t_command *cmd;
    int index = 1;
    while ((cmd = (t_command *)iter_next(&it)) != NULL) {
        print_command(cmd, index++);
    }
}
References iter_next(), iter_start(), print_command(), and s_gen_list::size.
print_redirect()
void print_redirect (t_redirect * redir)
Definition at line 156 of file minishell.c.
{
    if (!redir) return;
    const char *type_str;
    switch (redir->redirect_simbol) {
        case LEFT_REDIRECT: type_str = "<"; break;
        case RIGHT_REDIRECT: type_str = ">"; break;
        case DOUBLE_LEFT_REDIRECT: type_str = "<<"; break;
        case DOUBLE_RIGHT_REDIRECT: type_str = ">>"; break;
        case NONE: type_str = "NONE"; break;
        case ERROR: type_str = "ERROR"; break;
        default: type_str = "UNKNOWN"; break;
    }
    printf("    Redirect: %s %s\n", type_str, redir->file);
}
References DOUBLE_LEFT_REDIRECT, DOUBLE_RIGHT_REDIRECT, ERROR, s_redirect::file, LEFT_REDIRECT, NONE, s_redirect::redirect_simbol, and RIGHT_REDIRECT.
Referenced by print_command().
print_tokens()
void print_tokens (t_gen_list * tokens)
Definition at line 114 of file minishell.c.
{
    t_iter      it;
    t_token     *tok;
    const char  *type_str;
    if (!tokens)
        return ;
    it = iter_start(tokens);
    while ((tok = (t_token *)iter_next(&it)) != NULL)
    {
        switch (tok->type)
        {
        case TOKEN_CMD:
            type_str = "CMD";
            break ;
        case TOKEN_ARG:
            type_str = "ARG";
            break ;
        case TOKEN_PIPE:
            type_str = "PIPE";
            break ;
        case TOKEN_REDIR_IN:
            type_str = "REDIR_IN";
            break ;
        case TOKEN_REDIR_OUT:
            type_str = "REDIR_OUT";
            break ;
        case TOKEN_REDIR_APPEND:
            type_str = "REDIR_APPEND";
            break ;
        case TOKEN_HEREDOC:
            type_str = "HEREDOC";
            break ;
        default:
            type_str = "UNKNOWN";
            break ;
        }
        printf("[%s] : [%s]\n", type_str, tok->value);
    }
}
References iter_next(), iter_start(), TOKEN_ARG, TOKEN_CMD, TOKEN_HEREDOC, TOKEN_PIPE, TOKEN_REDIR_APPEND, TOKEN_REDIR_IN, TOKEN_REDIR_OUT, s_token::type, and s_token::value.
sigint_handler()
void sigint_handler (int sig)
Definition at line 89 of file minishell.c.
{
    (void)sig;
    g_signal = SIGINT;
    write(1, "\n", 1);
    rl_on_new_line();
    rl_replace_line("", 0);
    rl_redisplay();
}
References g_signal.
Referenced by signals_init().
signals_init()
void signals_init (void)
Definition at line 99 of file minishell.c.
{
    struct sigaction    sa_int;
    struct sigaction    sa_quit;
    sa_int.sa_handler = sigint_handler;
    sigemptyset(&sa_int.sa_mask);
    sa_int.sa_flags = SA_RESTART;
    sigaction(SIGINT, &sa_int, NULL);
    sa_quit.sa_handler = SIG_IGN;
    sigemptyset(&sa_quit.sa_mask);
    sa_quit.sa_flags = SA_RESTART;
    sigaction(SIGQUIT, &sa_quit, NULL);
}
References sigint_handler().
Referenced by main().
username()
char * username (t_gen_list * env)
Definition at line 79 of file minishell.c.
{
    char    *username;
    username = env_get(env, "LOGNAME");
    if (!username)
        return (ft_strdup("minishell%"));
    return (ft_strjoin(username, "%>$"));
}
References env_get(), ft_strdup(), ft_strjoin(), and username().
Referenced by main(), and username().
Variable Documentation
g_signal
volatile sig_atomic_t g_signal = 0
Definition at line 27 of file minishell.c.
Referenced by sigint_handler().