Kyle's Doxygen Test: include/redirect_asignation.h File Reference
redirect_asignation.h File Reference
#include "list.h"
Classes
struct s_redirect
Typedefs
typedef enum e_redirect_type t_redirect_type
typedef struct s_redirect t_redirect
Enumerations
enum e_redirect_type {
LEFT_REDIRECT , RIGHT_REDIRECT , DOUBLE_LEFT_REDIRECT , DOUBLE_RIGHT_REDIRECT ,
NONE , ERROR
}
Functions
t_redirect * init_redirect (char *file, t_redirect_type redirect_type)
t_gen_list * get_redirects_from_str_arr (char *str)
void destroy_redirect (void *redirect)
Typedef Documentation
t_redirect
typedef struct s_redirect t_redirect
t_redirect_type
typedef enum e_redirect_type t_redirect_type
Enumeration Type Documentation
e_redirect_type
enum e_redirect_type
Enumerator
LEFT_REDIRECT
RIGHT_REDIRECT
DOUBLE_LEFT_REDIRECT
DOUBLE_RIGHT_REDIRECT
NONE
ERROR
Definition at line 5 of file redirect_asignation.h.
{
    LEFT_REDIRECT,
    RIGHT_REDIRECT,
    DOUBLE_LEFT_REDIRECT,
    DOUBLE_RIGHT_REDIRECT,
    NONE,
    ERROR,
}                   t_redirect_type;
Function Documentation
destroy_redirect()
void destroy_redirect (void * redirect)
Definition at line 97 of file redirect_asignation.c.
{
    t_redirect  *aux;
    aux = (t_redirect *)redirect;
    free(aux->file);
    free(aux);
}
References s_redirect::file.
Referenced by destroy_command().
get_redirects_from_str_arr()
t_gen_list * get_redirects_from_str_arr (char * str)
Definition at line 9 of file redirect_asignation.c.
{
    t_gen_list  *redirects;
    t_redirect  *current_node_value;
    char        *current_redirecction;
    int         i;
    redirects = init_list();
    current_redirecction = first_redirection(str);
    while (current_redirecction != NULL)
    {
        current_node_value = init_redirect(get_file_from_str(str,
                    current_redirecction),
                get_redirection_type_from_str(current_redirecction));
        push_end(redirects, current_node_value);
        i = special_char(str, current_redirecction)
            + (int)ft_strlen(current_redirecction);
        str = str + i;
        current_redirecction = first_redirection(str);
    }
    if (redirects->head == NULL)
    {
        free(redirects);
        redirects = NULL;
    }
    return (redirects);
}
References first_redirection(), ft_strlen(), get_file_from_str(), get_redirection_type_from_str(), s_gen_list::head, init_list(), init_redirect(), push_end(), and special_char().
init_redirect()
t_redirect * init_redirect (char * file, t_redirect_type redirect_type)
Definition at line 84 of file redirect_asignation.c.
{
    t_redirect *r = malloc(sizeof(t_redirect));
    if (!r) return NULL;
    r->redirect_simbol = redirect_type;
    if (file) {
        r->file = malloc(ft_strlen(file) + 1);
        if (!r->file) { free(r); return NULL; }
        ft_strlcpy(r->file, file, ft_strlen(file) + 1);
    } else {
        r->file = NULL;
    }
    return r;
}
References s_redirect::file, ft_strlcpy(), ft_strlen(), and s_redirect::redirect_simbol.
Referenced by get_redirects_from_str_arr(), and parse_tokens_to_commands().