Kyle's Doxygen Test: src/redirect_asignation.c File Reference
redirect_asignation.c File Reference
#include "../include/redirect_asignation.h"
#include "../include/util.h"
#include "../libft/libft.h"
Functions
static t_redirect_type get_redirection_type_from_str (char *str)
static char * first_redirection (char *str)
static char * get_file_from_str (char *str, char *redirection)
t_gen_list * get_redirects_from_str_arr (char *str)
t_redirect * init_redirect (char *file, t_redirect_type redirect_type)
void destroy_redirect (void *redirect)
Function Documentation
destroy_redirect()
void destroy_redirect (void * redirect)
Definition at line 97 of file redirect_asignation.c.
{
    t_redirect  *aux;
    aux = (t_redirect *)redirect;
    free(aux->file);
    free(aux);
}
References s_redirect::file.
Referenced by destroy_command().
first_redirection()
static char * first_redirection (char * str) static
Definition at line 36 of file redirect_asignation.c.
{
    int l;
    int r;
    int dl;
    int dr;
    l = special_char(str, "<");
    r = special_char(str, ">");
    dl = special_char(str, "<<");
    dr = special_char(str, ">>");
    if (l < r && l < dl && l < dr)
        return ("<");
    if (r < l && r < dl && r < dr)
        return (">");
    if (dl < r && dl < l && dl < dr)
        return ("<<");
    if (dr < l && dr < dl && dr < r)
        return (">>");
    return (NULL);
}
References special_char().
Referenced by get_redirects_from_str_arr().
get_file_from_str()
static char * get_file_from_str (char * str, char * redirection) static
Definition at line 58 of file redirect_asignation.c.
{
    int end;
    int start;
    start = special_char(str, redirection);
    start++;
    while (str[start] && ft_ispace(str[start]) == 1)
        start++;
    end = start;
    while (str[end] && ft_ispace(str[end] == 0))
        end++;
    return (ft_substr(str, start, (size_t)end));
}
References ft_ispace(), ft_substr(), and special_char().
Referenced by get_redirects_from_str_arr().
get_redirection_type_from_str()
static t_redirect_type get_redirection_type_from_str (char * str) static
Definition at line 72 of file redirect_asignation.c.
{
    if (ft_strncmp(str, "<", 1) == 0)
        return (LEFT_REDIRECT);
    if (ft_strncmp(str, ">", 1) == 0)
        return (RIGHT_REDIRECT);
    if (ft_strncmp(str, ">>", 2) == 0)
        return (DOUBLE_RIGHT_REDIRECT);
    if (ft_strncmp(str, "<<", 2) == 0)
        return (DOUBLE_LEFT_REDIRECT);
    return (ERROR);
}
References DOUBLE_LEFT_REDIRECT, DOUBLE_RIGHT_REDIRECT, ERROR, ft_strncmp(), LEFT_REDIRECT, and RIGHT_REDIRECT.
Referenced by get_redirects_from_str_arr().
get_redirects_from_str_arr()
t_gen_list * get_redirects_from_str_arr (char * str)
Definition at line 9 of file redirect_asignation.c.
{
    t_gen_list  *redirects;
    t_redirect  *current_node_value;
    char        *current_redirecction;
    int         i;
    redirects = init_list();
    current_redirecction = first_redirection(str);
    while (current_redirecction != NULL)
    {
        current_node_value = init_redirect(get_file_from_str(str,
                    current_redirecction),
                get_redirection_type_from_str(current_redirecction));
        push_end(redirects, current_node_value);
        i = special_char(str, current_redirecction)
            + (int)ft_strlen(current_redirecction);
        str = str + i;
        current_redirecction = first_redirection(str);
    }
    if (redirects->head == NULL)
    {
        free(redirects);
        redirects = NULL;
    }
    return (redirects);
}
References first_redirection(), ft_strlen(), get_file_from_str(), get_redirection_type_from_str(), s_gen_list::head, init_list(), init_redirect(), push_end(), and special_char().
init_redirect()
t_redirect * init_redirect (char * file, t_redirect_type redirect_type)
Definition at line 84 of file redirect_asignation.c.
{
    t_redirect *r = malloc(sizeof(t_redirect));
    if (!r) return NULL;
    r->redirect_simbol = redirect_type;
    if (file) {
        r->file = malloc(ft_strlen(file) + 1);
        if (!r->file) { free(r); return NULL; }
        ft_strlcpy(r->file, file, ft_strlen(file) + 1);
    } else {
        r->file = NULL;
    }
    return r;
}
References s_redirect::file, ft_strlcpy(), ft_strlen(), and s_redirect::redirect_simbol.
Referenced by get_redirects_from_str_arr(), and parse_tokens_to_commands().