Kyle's Doxygen Test: src/tokenizer.c File Reference
tokenizer.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>
#include "../list/list.h"
#include "../include/tokenizer.h"
#include "../libft/libft.h"
#include "../include/util.h"
Functions
static char * ft_strndup (const char *s, size_t n)
static int is_space (char c)
static int is_operator_char (char c)
static int match_two_char_op (const char *s, size_t pos, const char *op)
static t_token * create_token (t_token_type type, char *value)
static t_token_type operator_type (const char *op, size_t len)
t_gen_list * tokenize (const char *line)
void destroy_token (t_token *token)
Function Documentation
create_token()
static t_token * create_token (t_token_type type, char * value) static
Definition at line 21 of file tokenizer.c.
{
    t_token *tok = malloc(sizeof(t_token));
    if (!tok) return NULL;
    tok->type = type;
    tok->value = value;
    return tok;
}
References s_token::type, and s_token::value.
Referenced by tokenize().
destroy_token()
void destroy_token (t_token * token)
Definition at line 119 of file tokenizer.c.
{
    if (!token)
        return;
    if (token->value)
    {
        free(token->value);
        token->value = NULL;
    }
    free(token);
}
References s_token::value.
Referenced by destroy_token_data().
ft_strndup()
static char * ft_strndup (const char * s, size_t n) static
Definition at line 10 of file tokenizer.c.
{
    char *p = malloc(n + 1); size_t i; if (!p) return NULL;
    for (i = 0; i < n && s[i]; i++) p[i] = s[i]; p[i] = '\0'; return p;
}
Referenced by tokenize().
is_operator_char()
static int is_operator_char (char c) static
Definition at line 16 of file tokenizer.c.
{ return c == '|' || c == '>' || c == '<'; }
Referenced by tokenize().
is_space()
static int is_space (char c) static
Definition at line 15 of file tokenizer.c.
{ return c == ' ' || c == '\t'; }
Referenced by tokenize().
match_two_char_op()
static int match_two_char_op (const char * s, size_t pos, const char * op) static
Definition at line 17 of file tokenizer.c.
{
    return s[pos] && s[pos+1] && s[pos] == op[0] && s[pos+1] == op[1];
}
Referenced by tokenize().
operator_type()
static t_token_type operator_type (const char * op, size_t len) static
Definition at line 29 of file tokenizer.c.
{
    if (len == 1) {
        if (op[0] == '|') return TOKEN_PIPE;
        if (op[0] == '<') return TOKEN_REDIR_IN;
        if (op[0] == '>') return TOKEN_REDIR_OUT;
    } else if (len == 2) {
        if (op[0] == '<' && op[1] == '<') return TOKEN_HEREDOC;
        if (op[0] == '>' && op[1] == '>') return TOKEN_REDIR_APPEND;
    }
    return TOKEN_ARG; // fallback
}
References TOKEN_ARG, TOKEN_HEREDOC, TOKEN_PIPE, TOKEN_REDIR_APPEND, TOKEN_REDIR_IN, and TOKEN_REDIR_OUT.
Referenced by tokenize().
tokenize()
t_gen_list * tokenize (const char * line)
Definition at line 41 of file tokenizer.c.
{
    size_t i = 0, len = ft_strlen(line);
    t_gen_list *tokens_list = init_list();
    if (!tokens_list) return NULL;
    bool expect_cmd = true; // El siguiente token no operador será CMD
    bool next_is_redir_arg = false; // El siguiente token después de >, >>, <, <<
    while (i < len) {
        while (i < len && is_space(line[i])) i++;
        if (i >= len) break;
        /* operadores de dos caracteres */
        if (match_two_char_op(line, i, ">>") || match_two_char_op(line, i, "<<")) {
            char *op = ft_strndup(line + i, 2);
            t_token *tok = create_token(operator_type(op, 2), op);
            push_end(tokens_list, tok);
            i += 2;
            if (tok->type == TOKEN_REDIR_APPEND || tok->type == TOKEN_HEREDOC)
                next_is_redir_arg = true;
            continue;
        }
        /* operadores de un caracter */
        if (is_operator_char(line[i])) {
            char *op = ft_strndup(line + i, 1);
            t_token *tok = create_token(operator_type(op, 1), op);
            push_end(tokens_list, tok);
            i++;
            if (tok->type == TOKEN_REDIR_IN || tok->type == TOKEN_REDIR_OUT)
                next_is_redir_arg = true;
            else if (tok->type == TOKEN_PIPE)
                expect_cmd = true;
            continue;
        }
        /* palabras */
        size_t start = i;
        char *buf = NULL; size_t bcap = 0, blen = 0;
        while (i < len && !is_space(line[i]) && !is_operator_char(line[i])) {
            char c = line[i];
            if (c == '\'') { i++; while(i<len && line[i]!='\''){ if(blen+1>=bcap){ size_t nc=(bcap?bcap*2:64); char*tmp=realloc(buf,nc); buf=tmp;bcap=nc;} buf[blen++]=line[i++]; } if(i<len&&line[i]=='\'') i++; }
            else if(c=='"'){ i++; while(i<len && line[i]!='"'){ if(line[i]=='\\'&&i+1<len){ if(blen+1>=bcap){ size_t nc=(bcap?bcap*2:64); char*tmp=realloc(buf,nc); buf=tmp;bcap=nc; } buf[blen++]=line[i+1]; i+=2; } else { if(blen+1>=bcap){ size_t nc=(bcap?bcap*2:64); char*tmp=realloc(buf,nc); buf=tmp;bcap=nc;} buf[blen++]=line[i++]; } } if(i<len&&line[i]=='"') i++; }
            else if(c=='\\'&&i+1<len){ if(blen+1>=bcap){ size_t nc=(bcap?bcap*2:64); char*tmp=realloc(buf,nc); buf=tmp;bcap=nc;} buf[blen++]=line[i+1]; i+=2; }
            else{ if(blen+1>=bcap){ size_t nc=(bcap?bcap*2:64); char*tmp=realloc(buf,nc); buf=tmp;bcap=nc;} buf[blen++]=c; i++; }
        }
        char *word;
        if(blen==0){ size_t wlen=i-start; word=ft_strndup(line+start,wlen); if(!word) goto error; }
        else { word=malloc(blen+1); if(!word) goto error; for(size_t k=0;k<blen;k++) word[k]=buf[k]; word[blen]='\0'; free(buf); }
        t_token_type type;
        if (next_is_redir_arg) {
            type = TOKEN_ARG; // siempre argumento si viene después de redirección
            next_is_redir_arg = false;
        } else if (expect_cmd) {
            type = TOKEN_CMD;
            expect_cmd = false;
        } else {
            type = TOKEN_ARG;
        }
        t_token *tok = create_token(type, word);
        push_end(tokens_list, tok);
    }
    return tokens_list;
error:
    if(tokens_list) destroy_gen_list(tokens_list, free);
    return NULL;
}
References create_token(), destroy_gen_list(), ft_strlen(), ft_strndup(), init_list(), is_operator_char(), is_space(), match_two_char_op(), operator_type(), push_end(), TOKEN_ARG, TOKEN_CMD, TOKEN_HEREDOC, TOKEN_PIPE, TOKEN_REDIR_APPEND, TOKEN_REDIR_IN, TOKEN_REDIR_OUT, and s_token::type.
Referenced by main().