Kyle's Doxygen Test: include/util.h File Reference
util.h File Reference
Functions
char ** ft_split2 (char const *s, char c)
int ft_ispace (char c)
int special_char (char *str, char *c)
char * get_next_argument (char *c, char *str)
Function Documentation
ft_ispace()
int ft_ispace (char c)
Definition at line 17 of file path_utils.c.
{
    if (c == '\n' || c == ' ' || c == '\t')
        return (1);
    return (0);
}
Referenced by get_file_from_str(), and history_checker().
ft_split2()
char ** ft_split2 (char const * s, char c)
Definition at line 137 of file ft_split2.0.c.
{
    char    **p3;
    size_t  size;
    p3 = NULL;
    size = 0;
    if (!s)
        return (NULL);
    p3 = (char **)ft_calloc((ft_worldette(s, c) + 1), sizeof(char *));
    if (!p3)
        return (NULL);
    return (ft_rapt(s, c, p3, size));
}
References ft_calloc(), ft_rapt(), and ft_worldette().
Referenced by export_execute().
get_next_argument()
char * get_next_argument (char * c, char * str)
Definition at line 49 of file path_utils.c.
{
    int     i;
    size_t  len;
    len = ft_strlen(c);
    i = 0;
    while (str[i])
    {
        if (ft_strncmp(str, c, len))
            break ;
        i++;
    }
    return (str + i + (int)len);
}
References ft_strlen(), and ft_strncmp().
special_char()
int special_char (char * str, char * c)
Definition at line 23 of file path_utils.c.
{
    int     i;
    int     b1;
    int     b2;
    size_t  len;
    if (!str || !c)
        return ((int)ft_strlen(str) + 1);
    len = ft_strlen(c);
    i = 0;
    b1 = 0;
    b2 = 0;
    while (str[i])
    {
        if (str[i] == *"'" && b2 % 2 == 0)
            b1++;
        if (str[i] == '"' && b1 % 2 == 0)
            b2++;
        if (ft_strncmp(str + i, c, len) == 0 && b1 % 2 == 0 && b2 % 2 == 0)
            return (i);
        i++;
    }
    return ((int)ft_strlen(str) + 1);
}
References ft_strlen(), and ft_strncmp().
Referenced by first_redirection(), get_file_from_str(), and get_redirects_from_str_arr().